// Code generated by MockGen. DO NOT EDIT.
// Source: rollback.go
//
// Generated by this command:
//
//	mockgen -source=rollback.go -destination=mock/rollback.go -package=mock -typed
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/baking-bad/bcdhub/internal/models"
	account "github.com/baking-bad/bcdhub/internal/models/account"
	bigmapdiff "github.com/baking-bad/bcdhub/internal/models/bigmapdiff"
	contract "github.com/baking-bad/bcdhub/internal/models/contract"
	migration "github.com/baking-bad/bcdhub/internal/models/migration"
	operation "github.com/baking-bad/bcdhub/internal/models/operation"
	stats "github.com/baking-bad/bcdhub/internal/models/stats"
	ticket "github.com/baking-bad/bcdhub/internal/models/ticket"
	gomock "go.uber.org/mock/gomock"
)

// MockRollback is a mock of Rollback interface.
type MockRollback struct {
	ctrl     *gomock.Controller
	recorder *MockRollbackMockRecorder
}

// MockRollbackMockRecorder is the mock recorder for MockRollback.
type MockRollbackMockRecorder struct {
	mock *MockRollback
}

// NewMockRollback creates a new mock instance.
func NewMockRollback(ctrl *gomock.Controller) *MockRollback {
	mock := &MockRollback{ctrl: ctrl}
	mock.recorder = &MockRollbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRollback) EXPECT() *MockRollbackMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockRollback) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockRollbackMockRecorder) Commit() *RollbackCommitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockRollback)(nil).Commit))
	return &RollbackCommitCall{Call: call}
}

// RollbackCommitCall wrap *gomock.Call
type RollbackCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackCommitCall) Return(arg0 error) *RollbackCommitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackCommitCall) Do(f func() error) *RollbackCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackCommitCall) DoAndReturn(f func() error) *RollbackCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAll mocks base method.
func (m *MockRollback) DeleteAll(ctx context.Context, model any, level int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, model, level)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockRollbackMockRecorder) DeleteAll(ctx, model, level any) *RollbackDeleteAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockRollback)(nil).DeleteAll), ctx, model, level)
	return &RollbackDeleteAllCall{Call: call}
}

// RollbackDeleteAllCall wrap *gomock.Call
type RollbackDeleteAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackDeleteAllCall) Return(arg0 int, arg1 error) *RollbackDeleteAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackDeleteAllCall) Do(f func(context.Context, any, int64) (int, error)) *RollbackDeleteAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackDeleteAllCall) DoAndReturn(f func(context.Context, any, int64) (int, error)) *RollbackDeleteAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteBigMapState mocks base method.
func (m *MockRollback) DeleteBigMapState(ctx context.Context, state bigmapdiff.BigMapState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBigMapState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBigMapState indicates an expected call of DeleteBigMapState.
func (mr *MockRollbackMockRecorder) DeleteBigMapState(ctx, state any) *RollbackDeleteBigMapStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBigMapState", reflect.TypeOf((*MockRollback)(nil).DeleteBigMapState), ctx, state)
	return &RollbackDeleteBigMapStateCall{Call: call}
}

// RollbackDeleteBigMapStateCall wrap *gomock.Call
type RollbackDeleteBigMapStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackDeleteBigMapStateCall) Return(arg0 error) *RollbackDeleteBigMapStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackDeleteBigMapStateCall) Do(f func(context.Context, bigmapdiff.BigMapState) error) *RollbackDeleteBigMapStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackDeleteBigMapStateCall) DoAndReturn(f func(context.Context, bigmapdiff.BigMapState) error) *RollbackDeleteBigMapStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteScriptsConstants mocks base method.
func (m *MockRollback) DeleteScriptsConstants(ctx context.Context, scriptIds, constantsIds []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScriptsConstants", ctx, scriptIds, constantsIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScriptsConstants indicates an expected call of DeleteScriptsConstants.
func (mr *MockRollbackMockRecorder) DeleteScriptsConstants(ctx, scriptIds, constantsIds any) *RollbackDeleteScriptsConstantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScriptsConstants", reflect.TypeOf((*MockRollback)(nil).DeleteScriptsConstants), ctx, scriptIds, constantsIds)
	return &RollbackDeleteScriptsConstantsCall{Call: call}
}

// RollbackDeleteScriptsConstantsCall wrap *gomock.Call
type RollbackDeleteScriptsConstantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackDeleteScriptsConstantsCall) Return(arg0 error) *RollbackDeleteScriptsConstantsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackDeleteScriptsConstantsCall) Do(f func(context.Context, []int64, []int64) error) *RollbackDeleteScriptsConstantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackDeleteScriptsConstantsCall) DoAndReturn(f func(context.Context, []int64, []int64) error) *RollbackDeleteScriptsConstantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTicketBalances mocks base method.
func (m *MockRollback) DeleteTicketBalances(ctx context.Context, ticketIds []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTicketBalances", ctx, ticketIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTicketBalances indicates an expected call of DeleteTicketBalances.
func (mr *MockRollbackMockRecorder) DeleteTicketBalances(ctx, ticketIds any) *RollbackDeleteTicketBalancesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTicketBalances", reflect.TypeOf((*MockRollback)(nil).DeleteTicketBalances), ctx, ticketIds)
	return &RollbackDeleteTicketBalancesCall{Call: call}
}

// RollbackDeleteTicketBalancesCall wrap *gomock.Call
type RollbackDeleteTicketBalancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackDeleteTicketBalancesCall) Return(err error) *RollbackDeleteTicketBalancesCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackDeleteTicketBalancesCall) Do(f func(context.Context, []int64) error) *RollbackDeleteTicketBalancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackDeleteTicketBalancesCall) DoAndReturn(f func(context.Context, []int64) error) *RollbackDeleteTicketBalancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTickets mocks base method.
func (m *MockRollback) DeleteTickets(ctx context.Context, level int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTickets", ctx, level)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTickets indicates an expected call of DeleteTickets.
func (mr *MockRollbackMockRecorder) DeleteTickets(ctx, level any) *RollbackDeleteTicketsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTickets", reflect.TypeOf((*MockRollback)(nil).DeleteTickets), ctx, level)
	return &RollbackDeleteTicketsCall{Call: call}
}

// RollbackDeleteTicketsCall wrap *gomock.Call
type RollbackDeleteTicketsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackDeleteTicketsCall) Return(ids []int64, err error) *RollbackDeleteTicketsCall {
	c.Call = c.Call.Return(ids, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackDeleteTicketsCall) Do(f func(context.Context, int64) ([]int64, error)) *RollbackDeleteTicketsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackDeleteTicketsCall) DoAndReturn(f func(context.Context, int64) ([]int64, error)) *RollbackDeleteTicketsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLastAction mocks base method.
func (m *MockRollback) GetLastAction(ctx context.Context, addressIds ...int64) ([]models.LastAction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range addressIds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastAction", varargs...)
	ret0, _ := ret[0].([]models.LastAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAction indicates an expected call of GetLastAction.
func (mr *MockRollbackMockRecorder) GetLastAction(ctx any, addressIds ...any) *RollbackGetLastActionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, addressIds...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAction", reflect.TypeOf((*MockRollback)(nil).GetLastAction), varargs...)
	return &RollbackGetLastActionCall{Call: call}
}

// RollbackGetLastActionCall wrap *gomock.Call
type RollbackGetLastActionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackGetLastActionCall) Return(arg0 []models.LastAction, arg1 error) *RollbackGetLastActionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackGetLastActionCall) Do(f func(context.Context, ...int64) ([]models.LastAction, error)) *RollbackGetLastActionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackGetLastActionCall) DoAndReturn(f func(context.Context, ...int64) ([]models.LastAction, error)) *RollbackGetLastActionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMigrations mocks base method.
func (m *MockRollback) GetMigrations(ctx context.Context, level int64) ([]migration.Migration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMigrations", ctx, level)
	ret0, _ := ret[0].([]migration.Migration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMigrations indicates an expected call of GetMigrations.
func (mr *MockRollbackMockRecorder) GetMigrations(ctx, level any) *RollbackGetMigrationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMigrations", reflect.TypeOf((*MockRollback)(nil).GetMigrations), ctx, level)
	return &RollbackGetMigrationsCall{Call: call}
}

// RollbackGetMigrationsCall wrap *gomock.Call
type RollbackGetMigrationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackGetMigrationsCall) Return(arg0 []migration.Migration, arg1 error) *RollbackGetMigrationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackGetMigrationsCall) Do(f func(context.Context, int64) ([]migration.Migration, error)) *RollbackGetMigrationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackGetMigrationsCall) DoAndReturn(f func(context.Context, int64) ([]migration.Migration, error)) *RollbackGetMigrationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOperations mocks base method.
func (m *MockRollback) GetOperations(ctx context.Context, level int64) ([]operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperations", ctx, level)
	ret0, _ := ret[0].([]operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperations indicates an expected call of GetOperations.
func (mr *MockRollbackMockRecorder) GetOperations(ctx, level any) *RollbackGetOperationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperations", reflect.TypeOf((*MockRollback)(nil).GetOperations), ctx, level)
	return &RollbackGetOperationsCall{Call: call}
}

// RollbackGetOperationsCall wrap *gomock.Call
type RollbackGetOperationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackGetOperationsCall) Return(arg0 []operation.Operation, arg1 error) *RollbackGetOperationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackGetOperationsCall) Do(f func(context.Context, int64) ([]operation.Operation, error)) *RollbackGetOperationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackGetOperationsCall) DoAndReturn(f func(context.Context, int64) ([]operation.Operation, error)) *RollbackGetOperationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTicketUpdates mocks base method.
func (m *MockRollback) GetTicketUpdates(ctx context.Context, level int64) ([]ticket.TicketUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketUpdates", ctx, level)
	ret0, _ := ret[0].([]ticket.TicketUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketUpdates indicates an expected call of GetTicketUpdates.
func (mr *MockRollbackMockRecorder) GetTicketUpdates(ctx, level any) *RollbackGetTicketUpdatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketUpdates", reflect.TypeOf((*MockRollback)(nil).GetTicketUpdates), ctx, level)
	return &RollbackGetTicketUpdatesCall{Call: call}
}

// RollbackGetTicketUpdatesCall wrap *gomock.Call
type RollbackGetTicketUpdatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackGetTicketUpdatesCall) Return(arg0 []ticket.TicketUpdate, arg1 error) *RollbackGetTicketUpdatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackGetTicketUpdatesCall) Do(f func(context.Context, int64) ([]ticket.TicketUpdate, error)) *RollbackGetTicketUpdatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackGetTicketUpdatesCall) DoAndReturn(f func(context.Context, int64) ([]ticket.TicketUpdate, error)) *RollbackGetTicketUpdatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GlobalConstants mocks base method.
func (m *MockRollback) GlobalConstants(ctx context.Context, level int64) ([]contract.GlobalConstant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalConstants", ctx, level)
	ret0, _ := ret[0].([]contract.GlobalConstant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalConstants indicates an expected call of GlobalConstants.
func (mr *MockRollbackMockRecorder) GlobalConstants(ctx, level any) *RollbackGlobalConstantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalConstants", reflect.TypeOf((*MockRollback)(nil).GlobalConstants), ctx, level)
	return &RollbackGlobalConstantsCall{Call: call}
}

// RollbackGlobalConstantsCall wrap *gomock.Call
type RollbackGlobalConstantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackGlobalConstantsCall) Return(arg0 []contract.GlobalConstant, arg1 error) *RollbackGlobalConstantsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackGlobalConstantsCall) Do(f func(context.Context, int64) ([]contract.GlobalConstant, error)) *RollbackGlobalConstantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackGlobalConstantsCall) DoAndReturn(f func(context.Context, int64) ([]contract.GlobalConstant, error)) *RollbackGlobalConstantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastDiff mocks base method.
func (m *MockRollback) LastDiff(ctx context.Context, ptr int64, keyHash string, skipRemoved bool) (bigmapdiff.BigMapDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastDiff", ctx, ptr, keyHash, skipRemoved)
	ret0, _ := ret[0].(bigmapdiff.BigMapDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastDiff indicates an expected call of LastDiff.
func (mr *MockRollbackMockRecorder) LastDiff(ctx, ptr, keyHash, skipRemoved any) *RollbackLastDiffCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastDiff", reflect.TypeOf((*MockRollback)(nil).LastDiff), ctx, ptr, keyHash, skipRemoved)
	return &RollbackLastDiffCall{Call: call}
}

// RollbackLastDiffCall wrap *gomock.Call
type RollbackLastDiffCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackLastDiffCall) Return(arg0 bigmapdiff.BigMapDiff, arg1 error) *RollbackLastDiffCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackLastDiffCall) Do(f func(context.Context, int64, string, bool) (bigmapdiff.BigMapDiff, error)) *RollbackLastDiffCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackLastDiffCall) DoAndReturn(f func(context.Context, int64, string, bool) (bigmapdiff.BigMapDiff, error)) *RollbackLastDiffCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Protocols mocks base method.
func (m *MockRollback) Protocols(ctx context.Context, level int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protocols", ctx, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protocols indicates an expected call of Protocols.
func (mr *MockRollbackMockRecorder) Protocols(ctx, level any) *RollbackProtocolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protocols", reflect.TypeOf((*MockRollback)(nil).Protocols), ctx, level)
	return &RollbackProtocolsCall{Call: call}
}

// RollbackProtocolsCall wrap *gomock.Call
type RollbackProtocolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackProtocolsCall) Return(arg0 error) *RollbackProtocolsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackProtocolsCall) Do(f func(context.Context, int64) error) *RollbackProtocolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackProtocolsCall) DoAndReturn(f func(context.Context, int64) error) *RollbackProtocolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Rollback mocks base method.
func (m *MockRollback) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockRollbackMockRecorder) Rollback() *RollbackRollbackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockRollback)(nil).Rollback))
	return &RollbackRollbackCall{Call: call}
}

// RollbackRollbackCall wrap *gomock.Call
type RollbackRollbackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackRollbackCall) Return(arg0 error) *RollbackRollbackCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackRollbackCall) Do(f func() error) *RollbackRollbackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackRollbackCall) DoAndReturn(f func() error) *RollbackRollbackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveBigMapState mocks base method.
func (m *MockRollback) SaveBigMapState(ctx context.Context, state bigmapdiff.BigMapState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBigMapState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBigMapState indicates an expected call of SaveBigMapState.
func (mr *MockRollbackMockRecorder) SaveBigMapState(ctx, state any) *RollbackSaveBigMapStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBigMapState", reflect.TypeOf((*MockRollback)(nil).SaveBigMapState), ctx, state)
	return &RollbackSaveBigMapStateCall{Call: call}
}

// RollbackSaveBigMapStateCall wrap *gomock.Call
type RollbackSaveBigMapStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackSaveBigMapStateCall) Return(arg0 error) *RollbackSaveBigMapStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackSaveBigMapStateCall) Do(f func(context.Context, bigmapdiff.BigMapState) error) *RollbackSaveBigMapStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackSaveBigMapStateCall) DoAndReturn(f func(context.Context, bigmapdiff.BigMapState) error) *RollbackSaveBigMapStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Scripts mocks base method.
func (m *MockRollback) Scripts(ctx context.Context, level int64) ([]contract.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scripts", ctx, level)
	ret0, _ := ret[0].([]contract.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scripts indicates an expected call of Scripts.
func (mr *MockRollbackMockRecorder) Scripts(ctx, level any) *RollbackScriptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scripts", reflect.TypeOf((*MockRollback)(nil).Scripts), ctx, level)
	return &RollbackScriptsCall{Call: call}
}

// RollbackScriptsCall wrap *gomock.Call
type RollbackScriptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackScriptsCall) Return(arg0 []contract.Script, arg1 error) *RollbackScriptsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackScriptsCall) Do(f func(context.Context, int64) ([]contract.Script, error)) *RollbackScriptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackScriptsCall) DoAndReturn(f func(context.Context, int64) ([]contract.Script, error)) *RollbackScriptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StatesChangedAtLevel mocks base method.
func (m *MockRollback) StatesChangedAtLevel(ctx context.Context, level int64) ([]bigmapdiff.BigMapState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatesChangedAtLevel", ctx, level)
	ret0, _ := ret[0].([]bigmapdiff.BigMapState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatesChangedAtLevel indicates an expected call of StatesChangedAtLevel.
func (mr *MockRollbackMockRecorder) StatesChangedAtLevel(ctx, level any) *RollbackStatesChangedAtLevelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatesChangedAtLevel", reflect.TypeOf((*MockRollback)(nil).StatesChangedAtLevel), ctx, level)
	return &RollbackStatesChangedAtLevelCall{Call: call}
}

// RollbackStatesChangedAtLevelCall wrap *gomock.Call
type RollbackStatesChangedAtLevelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackStatesChangedAtLevelCall) Return(arg0 []bigmapdiff.BigMapState, arg1 error) *RollbackStatesChangedAtLevelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackStatesChangedAtLevelCall) Do(f func(context.Context, int64) ([]bigmapdiff.BigMapState, error)) *RollbackStatesChangedAtLevelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackStatesChangedAtLevelCall) DoAndReturn(f func(context.Context, int64) ([]bigmapdiff.BigMapState, error)) *RollbackStatesChangedAtLevelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TicketBalances mocks base method.
func (m *MockRollback) TicketBalances(ctx context.Context, balances ...*ticket.Balance) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range balances {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TicketBalances", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// TicketBalances indicates an expected call of TicketBalances.
func (mr *MockRollbackMockRecorder) TicketBalances(ctx any, balances ...any) *RollbackTicketBalancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, balances...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TicketBalances", reflect.TypeOf((*MockRollback)(nil).TicketBalances), varargs...)
	return &RollbackTicketBalancesCall{Call: call}
}

// RollbackTicketBalancesCall wrap *gomock.Call
type RollbackTicketBalancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackTicketBalancesCall) Return(arg0 error) *RollbackTicketBalancesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackTicketBalancesCall) Do(f func(context.Context, ...*ticket.Balance) error) *RollbackTicketBalancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackTicketBalancesCall) DoAndReturn(f func(context.Context, ...*ticket.Balance) error) *RollbackTicketBalancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateAccountStats mocks base method.
func (m *MockRollback) UpdateAccountStats(ctx context.Context, account account.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountStats", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountStats indicates an expected call of UpdateAccountStats.
func (mr *MockRollbackMockRecorder) UpdateAccountStats(ctx, account any) *RollbackUpdateAccountStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountStats", reflect.TypeOf((*MockRollback)(nil).UpdateAccountStats), ctx, account)
	return &RollbackUpdateAccountStatsCall{Call: call}
}

// RollbackUpdateAccountStatsCall wrap *gomock.Call
type RollbackUpdateAccountStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackUpdateAccountStatsCall) Return(arg0 error) *RollbackUpdateAccountStatsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackUpdateAccountStatsCall) Do(f func(context.Context, account.Account) error) *RollbackUpdateAccountStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackUpdateAccountStatsCall) DoAndReturn(f func(context.Context, account.Account) error) *RollbackUpdateAccountStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStats mocks base method.
func (m *MockRollback) UpdateStats(ctx context.Context, stats stats.Stats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStats", ctx, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStats indicates an expected call of UpdateStats.
func (mr *MockRollbackMockRecorder) UpdateStats(ctx, stats any) *RollbackUpdateStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStats", reflect.TypeOf((*MockRollback)(nil).UpdateStats), ctx, stats)
	return &RollbackUpdateStatsCall{Call: call}
}

// RollbackUpdateStatsCall wrap *gomock.Call
type RollbackUpdateStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackUpdateStatsCall) Return(arg0 error) *RollbackUpdateStatsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackUpdateStatsCall) Do(f func(context.Context, stats.Stats) error) *RollbackUpdateStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackUpdateStatsCall) DoAndReturn(f func(context.Context, stats.Stats) error) *RollbackUpdateStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTicket mocks base method.
func (m *MockRollback) UpdateTicket(ctx context.Context, ticket ticket.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicket", ctx, ticket)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockRollbackMockRecorder) UpdateTicket(ctx, ticket any) *RollbackUpdateTicketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockRollback)(nil).UpdateTicket), ctx, ticket)
	return &RollbackUpdateTicketCall{Call: call}
}

// RollbackUpdateTicketCall wrap *gomock.Call
type RollbackUpdateTicketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RollbackUpdateTicketCall) Return(arg0 error) *RollbackUpdateTicketCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RollbackUpdateTicketCall) Do(f func(context.Context, ticket.Ticket) error) *RollbackUpdateTicketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RollbackUpdateTicketCall) DoAndReturn(f func(context.Context, ticket.Ticket) error) *RollbackUpdateTicketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
