// Code generated by MockGen. DO NOT EDIT.
// Source: rollback.go
//
// Generated by this command:
//
//	mockgen -source=rollback.go -destination=mock/rollback.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/baking-bad/bcdhub/internal/models"
	account "github.com/baking-bad/bcdhub/internal/models/account"
	bigmapdiff "github.com/baking-bad/bcdhub/internal/models/bigmapdiff"
	contract "github.com/baking-bad/bcdhub/internal/models/contract"
	migration "github.com/baking-bad/bcdhub/internal/models/migration"
	operation "github.com/baking-bad/bcdhub/internal/models/operation"
	stats "github.com/baking-bad/bcdhub/internal/models/stats"
	ticket "github.com/baking-bad/bcdhub/internal/models/ticket"
	gomock "go.uber.org/mock/gomock"
)

// MockRollback is a mock of Rollback interface.
type MockRollback struct {
	ctrl     *gomock.Controller
	recorder *MockRollbackMockRecorder
	isgomock struct{}
}

// MockRollbackMockRecorder is the mock recorder for MockRollback.
type MockRollbackMockRecorder struct {
	mock *MockRollback
}

// NewMockRollback creates a new mock instance.
func NewMockRollback(ctrl *gomock.Controller) *MockRollback {
	mock := &MockRollback{ctrl: ctrl}
	mock.recorder = &MockRollbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRollback) EXPECT() *MockRollbackMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockRollback) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockRollbackMockRecorder) Commit() *MockRollbackCommitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockRollback)(nil).Commit))
	return &MockRollbackCommitCall{Call: call}
}

// MockRollbackCommitCall wrap *gomock.Call
type MockRollbackCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackCommitCall) Return(arg0 error) *MockRollbackCommitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackCommitCall) Do(f func() error) *MockRollbackCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackCommitCall) DoAndReturn(f func() error) *MockRollbackCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAll mocks base method.
func (m *MockRollback) DeleteAll(ctx context.Context, model any, level int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, model, level)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockRollbackMockRecorder) DeleteAll(ctx, model, level any) *MockRollbackDeleteAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockRollback)(nil).DeleteAll), ctx, model, level)
	return &MockRollbackDeleteAllCall{Call: call}
}

// MockRollbackDeleteAllCall wrap *gomock.Call
type MockRollbackDeleteAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackDeleteAllCall) Return(arg0 int, arg1 error) *MockRollbackDeleteAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackDeleteAllCall) Do(f func(context.Context, any, int64) (int, error)) *MockRollbackDeleteAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackDeleteAllCall) DoAndReturn(f func(context.Context, any, int64) (int, error)) *MockRollbackDeleteAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteBigMapState mocks base method.
func (m *MockRollback) DeleteBigMapState(ctx context.Context, state bigmapdiff.BigMapState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBigMapState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBigMapState indicates an expected call of DeleteBigMapState.
func (mr *MockRollbackMockRecorder) DeleteBigMapState(ctx, state any) *MockRollbackDeleteBigMapStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBigMapState", reflect.TypeOf((*MockRollback)(nil).DeleteBigMapState), ctx, state)
	return &MockRollbackDeleteBigMapStateCall{Call: call}
}

// MockRollbackDeleteBigMapStateCall wrap *gomock.Call
type MockRollbackDeleteBigMapStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackDeleteBigMapStateCall) Return(arg0 error) *MockRollbackDeleteBigMapStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackDeleteBigMapStateCall) Do(f func(context.Context, bigmapdiff.BigMapState) error) *MockRollbackDeleteBigMapStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackDeleteBigMapStateCall) DoAndReturn(f func(context.Context, bigmapdiff.BigMapState) error) *MockRollbackDeleteBigMapStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteScriptsConstants mocks base method.
func (m *MockRollback) DeleteScriptsConstants(ctx context.Context, scriptIds, constantsIds []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScriptsConstants", ctx, scriptIds, constantsIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScriptsConstants indicates an expected call of DeleteScriptsConstants.
func (mr *MockRollbackMockRecorder) DeleteScriptsConstants(ctx, scriptIds, constantsIds any) *MockRollbackDeleteScriptsConstantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScriptsConstants", reflect.TypeOf((*MockRollback)(nil).DeleteScriptsConstants), ctx, scriptIds, constantsIds)
	return &MockRollbackDeleteScriptsConstantsCall{Call: call}
}

// MockRollbackDeleteScriptsConstantsCall wrap *gomock.Call
type MockRollbackDeleteScriptsConstantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackDeleteScriptsConstantsCall) Return(arg0 error) *MockRollbackDeleteScriptsConstantsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackDeleteScriptsConstantsCall) Do(f func(context.Context, []int64, []int64) error) *MockRollbackDeleteScriptsConstantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackDeleteScriptsConstantsCall) DoAndReturn(f func(context.Context, []int64, []int64) error) *MockRollbackDeleteScriptsConstantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTicketBalances mocks base method.
func (m *MockRollback) DeleteTicketBalances(ctx context.Context, ticketIds []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTicketBalances", ctx, ticketIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTicketBalances indicates an expected call of DeleteTicketBalances.
func (mr *MockRollbackMockRecorder) DeleteTicketBalances(ctx, ticketIds any) *MockRollbackDeleteTicketBalancesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTicketBalances", reflect.TypeOf((*MockRollback)(nil).DeleteTicketBalances), ctx, ticketIds)
	return &MockRollbackDeleteTicketBalancesCall{Call: call}
}

// MockRollbackDeleteTicketBalancesCall wrap *gomock.Call
type MockRollbackDeleteTicketBalancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackDeleteTicketBalancesCall) Return(err error) *MockRollbackDeleteTicketBalancesCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackDeleteTicketBalancesCall) Do(f func(context.Context, []int64) error) *MockRollbackDeleteTicketBalancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackDeleteTicketBalancesCall) DoAndReturn(f func(context.Context, []int64) error) *MockRollbackDeleteTicketBalancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTickets mocks base method.
func (m *MockRollback) DeleteTickets(ctx context.Context, level int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTickets", ctx, level)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTickets indicates an expected call of DeleteTickets.
func (mr *MockRollbackMockRecorder) DeleteTickets(ctx, level any) *MockRollbackDeleteTicketsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTickets", reflect.TypeOf((*MockRollback)(nil).DeleteTickets), ctx, level)
	return &MockRollbackDeleteTicketsCall{Call: call}
}

// MockRollbackDeleteTicketsCall wrap *gomock.Call
type MockRollbackDeleteTicketsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackDeleteTicketsCall) Return(ids []int64, err error) *MockRollbackDeleteTicketsCall {
	c.Call = c.Call.Return(ids, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackDeleteTicketsCall) Do(f func(context.Context, int64) ([]int64, error)) *MockRollbackDeleteTicketsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackDeleteTicketsCall) DoAndReturn(f func(context.Context, int64) ([]int64, error)) *MockRollbackDeleteTicketsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLastAction mocks base method.
func (m *MockRollback) GetLastAction(ctx context.Context, addressIds ...int64) ([]models.LastAction, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range addressIds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastAction", varargs...)
	ret0, _ := ret[0].([]models.LastAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAction indicates an expected call of GetLastAction.
func (mr *MockRollbackMockRecorder) GetLastAction(ctx any, addressIds ...any) *MockRollbackGetLastActionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, addressIds...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAction", reflect.TypeOf((*MockRollback)(nil).GetLastAction), varargs...)
	return &MockRollbackGetLastActionCall{Call: call}
}

// MockRollbackGetLastActionCall wrap *gomock.Call
type MockRollbackGetLastActionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackGetLastActionCall) Return(arg0 []models.LastAction, arg1 error) *MockRollbackGetLastActionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackGetLastActionCall) Do(f func(context.Context, ...int64) ([]models.LastAction, error)) *MockRollbackGetLastActionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackGetLastActionCall) DoAndReturn(f func(context.Context, ...int64) ([]models.LastAction, error)) *MockRollbackGetLastActionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMigrations mocks base method.
func (m *MockRollback) GetMigrations(ctx context.Context, level int64) ([]migration.Migration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMigrations", ctx, level)
	ret0, _ := ret[0].([]migration.Migration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMigrations indicates an expected call of GetMigrations.
func (mr *MockRollbackMockRecorder) GetMigrations(ctx, level any) *MockRollbackGetMigrationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMigrations", reflect.TypeOf((*MockRollback)(nil).GetMigrations), ctx, level)
	return &MockRollbackGetMigrationsCall{Call: call}
}

// MockRollbackGetMigrationsCall wrap *gomock.Call
type MockRollbackGetMigrationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackGetMigrationsCall) Return(arg0 []migration.Migration, arg1 error) *MockRollbackGetMigrationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackGetMigrationsCall) Do(f func(context.Context, int64) ([]migration.Migration, error)) *MockRollbackGetMigrationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackGetMigrationsCall) DoAndReturn(f func(context.Context, int64) ([]migration.Migration, error)) *MockRollbackGetMigrationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetOperations mocks base method.
func (m *MockRollback) GetOperations(ctx context.Context, level int64) ([]operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperations", ctx, level)
	ret0, _ := ret[0].([]operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperations indicates an expected call of GetOperations.
func (mr *MockRollbackMockRecorder) GetOperations(ctx, level any) *MockRollbackGetOperationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperations", reflect.TypeOf((*MockRollback)(nil).GetOperations), ctx, level)
	return &MockRollbackGetOperationsCall{Call: call}
}

// MockRollbackGetOperationsCall wrap *gomock.Call
type MockRollbackGetOperationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackGetOperationsCall) Return(arg0 []operation.Operation, arg1 error) *MockRollbackGetOperationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackGetOperationsCall) Do(f func(context.Context, int64) ([]operation.Operation, error)) *MockRollbackGetOperationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackGetOperationsCall) DoAndReturn(f func(context.Context, int64) ([]operation.Operation, error)) *MockRollbackGetOperationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTicketUpdates mocks base method.
func (m *MockRollback) GetTicketUpdates(ctx context.Context, level int64) ([]ticket.TicketUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketUpdates", ctx, level)
	ret0, _ := ret[0].([]ticket.TicketUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketUpdates indicates an expected call of GetTicketUpdates.
func (mr *MockRollbackMockRecorder) GetTicketUpdates(ctx, level any) *MockRollbackGetTicketUpdatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketUpdates", reflect.TypeOf((*MockRollback)(nil).GetTicketUpdates), ctx, level)
	return &MockRollbackGetTicketUpdatesCall{Call: call}
}

// MockRollbackGetTicketUpdatesCall wrap *gomock.Call
type MockRollbackGetTicketUpdatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackGetTicketUpdatesCall) Return(arg0 []ticket.TicketUpdate, arg1 error) *MockRollbackGetTicketUpdatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackGetTicketUpdatesCall) Do(f func(context.Context, int64) ([]ticket.TicketUpdate, error)) *MockRollbackGetTicketUpdatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackGetTicketUpdatesCall) DoAndReturn(f func(context.Context, int64) ([]ticket.TicketUpdate, error)) *MockRollbackGetTicketUpdatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GlobalConstants mocks base method.
func (m *MockRollback) GlobalConstants(ctx context.Context, level int64) ([]contract.GlobalConstant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalConstants", ctx, level)
	ret0, _ := ret[0].([]contract.GlobalConstant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalConstants indicates an expected call of GlobalConstants.
func (mr *MockRollbackMockRecorder) GlobalConstants(ctx, level any) *MockRollbackGlobalConstantsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalConstants", reflect.TypeOf((*MockRollback)(nil).GlobalConstants), ctx, level)
	return &MockRollbackGlobalConstantsCall{Call: call}
}

// MockRollbackGlobalConstantsCall wrap *gomock.Call
type MockRollbackGlobalConstantsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackGlobalConstantsCall) Return(arg0 []contract.GlobalConstant, arg1 error) *MockRollbackGlobalConstantsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackGlobalConstantsCall) Do(f func(context.Context, int64) ([]contract.GlobalConstant, error)) *MockRollbackGlobalConstantsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackGlobalConstantsCall) DoAndReturn(f func(context.Context, int64) ([]contract.GlobalConstant, error)) *MockRollbackGlobalConstantsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastDiff mocks base method.
func (m *MockRollback) LastDiff(ctx context.Context, ptr int64, keyHash string, skipRemoved bool) (bigmapdiff.BigMapDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastDiff", ctx, ptr, keyHash, skipRemoved)
	ret0, _ := ret[0].(bigmapdiff.BigMapDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastDiff indicates an expected call of LastDiff.
func (mr *MockRollbackMockRecorder) LastDiff(ctx, ptr, keyHash, skipRemoved any) *MockRollbackLastDiffCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastDiff", reflect.TypeOf((*MockRollback)(nil).LastDiff), ctx, ptr, keyHash, skipRemoved)
	return &MockRollbackLastDiffCall{Call: call}
}

// MockRollbackLastDiffCall wrap *gomock.Call
type MockRollbackLastDiffCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackLastDiffCall) Return(arg0 bigmapdiff.BigMapDiff, arg1 error) *MockRollbackLastDiffCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackLastDiffCall) Do(f func(context.Context, int64, string, bool) (bigmapdiff.BigMapDiff, error)) *MockRollbackLastDiffCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackLastDiffCall) DoAndReturn(f func(context.Context, int64, string, bool) (bigmapdiff.BigMapDiff, error)) *MockRollbackLastDiffCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Protocols mocks base method.
func (m *MockRollback) Protocols(ctx context.Context, level int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protocols", ctx, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// Protocols indicates an expected call of Protocols.
func (mr *MockRollbackMockRecorder) Protocols(ctx, level any) *MockRollbackProtocolsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protocols", reflect.TypeOf((*MockRollback)(nil).Protocols), ctx, level)
	return &MockRollbackProtocolsCall{Call: call}
}

// MockRollbackProtocolsCall wrap *gomock.Call
type MockRollbackProtocolsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackProtocolsCall) Return(arg0 error) *MockRollbackProtocolsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackProtocolsCall) Do(f func(context.Context, int64) error) *MockRollbackProtocolsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackProtocolsCall) DoAndReturn(f func(context.Context, int64) error) *MockRollbackProtocolsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Rollback mocks base method.
func (m *MockRollback) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockRollbackMockRecorder) Rollback() *MockRollbackRollbackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockRollback)(nil).Rollback))
	return &MockRollbackRollbackCall{Call: call}
}

// MockRollbackRollbackCall wrap *gomock.Call
type MockRollbackRollbackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackRollbackCall) Return(arg0 error) *MockRollbackRollbackCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackRollbackCall) Do(f func() error) *MockRollbackRollbackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackRollbackCall) DoAndReturn(f func() error) *MockRollbackRollbackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveBigMapState mocks base method.
func (m *MockRollback) SaveBigMapState(ctx context.Context, state bigmapdiff.BigMapState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBigMapState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBigMapState indicates an expected call of SaveBigMapState.
func (mr *MockRollbackMockRecorder) SaveBigMapState(ctx, state any) *MockRollbackSaveBigMapStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBigMapState", reflect.TypeOf((*MockRollback)(nil).SaveBigMapState), ctx, state)
	return &MockRollbackSaveBigMapStateCall{Call: call}
}

// MockRollbackSaveBigMapStateCall wrap *gomock.Call
type MockRollbackSaveBigMapStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackSaveBigMapStateCall) Return(arg0 error) *MockRollbackSaveBigMapStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackSaveBigMapStateCall) Do(f func(context.Context, bigmapdiff.BigMapState) error) *MockRollbackSaveBigMapStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackSaveBigMapStateCall) DoAndReturn(f func(context.Context, bigmapdiff.BigMapState) error) *MockRollbackSaveBigMapStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Scripts mocks base method.
func (m *MockRollback) Scripts(ctx context.Context, level int64) ([]contract.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scripts", ctx, level)
	ret0, _ := ret[0].([]contract.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scripts indicates an expected call of Scripts.
func (mr *MockRollbackMockRecorder) Scripts(ctx, level any) *MockRollbackScriptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scripts", reflect.TypeOf((*MockRollback)(nil).Scripts), ctx, level)
	return &MockRollbackScriptsCall{Call: call}
}

// MockRollbackScriptsCall wrap *gomock.Call
type MockRollbackScriptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackScriptsCall) Return(arg0 []contract.Script, arg1 error) *MockRollbackScriptsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackScriptsCall) Do(f func(context.Context, int64) ([]contract.Script, error)) *MockRollbackScriptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackScriptsCall) DoAndReturn(f func(context.Context, int64) ([]contract.Script, error)) *MockRollbackScriptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StatesChangedAtLevel mocks base method.
func (m *MockRollback) StatesChangedAtLevel(ctx context.Context, level int64) ([]bigmapdiff.BigMapState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatesChangedAtLevel", ctx, level)
	ret0, _ := ret[0].([]bigmapdiff.BigMapState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatesChangedAtLevel indicates an expected call of StatesChangedAtLevel.
func (mr *MockRollbackMockRecorder) StatesChangedAtLevel(ctx, level any) *MockRollbackStatesChangedAtLevelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatesChangedAtLevel", reflect.TypeOf((*MockRollback)(nil).StatesChangedAtLevel), ctx, level)
	return &MockRollbackStatesChangedAtLevelCall{Call: call}
}

// MockRollbackStatesChangedAtLevelCall wrap *gomock.Call
type MockRollbackStatesChangedAtLevelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackStatesChangedAtLevelCall) Return(arg0 []bigmapdiff.BigMapState, arg1 error) *MockRollbackStatesChangedAtLevelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackStatesChangedAtLevelCall) Do(f func(context.Context, int64) ([]bigmapdiff.BigMapState, error)) *MockRollbackStatesChangedAtLevelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackStatesChangedAtLevelCall) DoAndReturn(f func(context.Context, int64) ([]bigmapdiff.BigMapState, error)) *MockRollbackStatesChangedAtLevelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TicketBalances mocks base method.
func (m *MockRollback) TicketBalances(ctx context.Context, balances ...*ticket.Balance) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range balances {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TicketBalances", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// TicketBalances indicates an expected call of TicketBalances.
func (mr *MockRollbackMockRecorder) TicketBalances(ctx any, balances ...any) *MockRollbackTicketBalancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, balances...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TicketBalances", reflect.TypeOf((*MockRollback)(nil).TicketBalances), varargs...)
	return &MockRollbackTicketBalancesCall{Call: call}
}

// MockRollbackTicketBalancesCall wrap *gomock.Call
type MockRollbackTicketBalancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackTicketBalancesCall) Return(arg0 error) *MockRollbackTicketBalancesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackTicketBalancesCall) Do(f func(context.Context, ...*ticket.Balance) error) *MockRollbackTicketBalancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackTicketBalancesCall) DoAndReturn(f func(context.Context, ...*ticket.Balance) error) *MockRollbackTicketBalancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateAccountStats mocks base method.
func (m *MockRollback) UpdateAccountStats(ctx context.Context, arg1 account.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountStats", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountStats indicates an expected call of UpdateAccountStats.
func (mr *MockRollbackMockRecorder) UpdateAccountStats(ctx, arg1 any) *MockRollbackUpdateAccountStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountStats", reflect.TypeOf((*MockRollback)(nil).UpdateAccountStats), ctx, arg1)
	return &MockRollbackUpdateAccountStatsCall{Call: call}
}

// MockRollbackUpdateAccountStatsCall wrap *gomock.Call
type MockRollbackUpdateAccountStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackUpdateAccountStatsCall) Return(arg0 error) *MockRollbackUpdateAccountStatsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackUpdateAccountStatsCall) Do(f func(context.Context, account.Account) error) *MockRollbackUpdateAccountStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackUpdateAccountStatsCall) DoAndReturn(f func(context.Context, account.Account) error) *MockRollbackUpdateAccountStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStats mocks base method.
func (m *MockRollback) UpdateStats(ctx context.Context, arg1 stats.Stats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStats", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStats indicates an expected call of UpdateStats.
func (mr *MockRollbackMockRecorder) UpdateStats(ctx, arg1 any) *MockRollbackUpdateStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStats", reflect.TypeOf((*MockRollback)(nil).UpdateStats), ctx, arg1)
	return &MockRollbackUpdateStatsCall{Call: call}
}

// MockRollbackUpdateStatsCall wrap *gomock.Call
type MockRollbackUpdateStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackUpdateStatsCall) Return(arg0 error) *MockRollbackUpdateStatsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackUpdateStatsCall) Do(f func(context.Context, stats.Stats) error) *MockRollbackUpdateStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackUpdateStatsCall) DoAndReturn(f func(context.Context, stats.Stats) error) *MockRollbackUpdateStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTicket mocks base method.
func (m *MockRollback) UpdateTicket(ctx context.Context, arg1 ticket.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicket", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTicket indicates an expected call of UpdateTicket.
func (mr *MockRollbackMockRecorder) UpdateTicket(ctx, arg1 any) *MockRollbackUpdateTicketCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicket", reflect.TypeOf((*MockRollback)(nil).UpdateTicket), ctx, arg1)
	return &MockRollbackUpdateTicketCall{Call: call}
}

// MockRollbackUpdateTicketCall wrap *gomock.Call
type MockRollbackUpdateTicketCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRollbackUpdateTicketCall) Return(arg0 error) *MockRollbackUpdateTicketCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRollbackUpdateTicketCall) Do(f func(context.Context, ticket.Ticket) error) *MockRollbackUpdateTicketCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRollbackUpdateTicketCall) DoAndReturn(f func(context.Context, ticket.Ticket) error) *MockRollbackUpdateTicketCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
