package macros

const (
	pair        = "PAIR"
	unpair      = "UNPAIR"
	unit        = "UNIT"
	failwith    = "FAILWITH"
	fail        = "FAIL"
	compare     = "COMPARE"
	eq          = "EQ"
	neq         = "NEQ"
	lt          = "LT"
	gt          = "GT"
	le          = "LE"
	ge          = "GE"
	ifp         = "IF"
	ifNone      = "IF_NONE"
	ifLeft      = "IF_LEFT"
	ifcmp       = "IFCMP"
	rename      = "RENAME"
	assert      = "ASSERT"
	assertNone  = "ASSERT_NONE"
	assertSome  = "ASSERT_SOME"
	assertLeft  = "ASSERT_LEFT"
	assertRight = "ASSERT_RIGHT"
	cmp         = "CMP"
	swap        = "SWAP"
	dip         = "DIP"
	dup         = "DUP"
	dig         = "DIG"
	car         = "CAR"
	cdr         = "CDR"
	drop        = "DROP"
	setCar      = "SET_CAR"
	setCdr      = "SET_CDR"
)
