// Code generated by MockGen. DO NOT EDIT.
// Source: tokenbalance/repository.go

// Package mock_tokenbalance is a generated GoMock package.
package tokenbalance

import (
	tb "github.com/baking-bad/bcdhub/internal/models/tokenbalance"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAccountBalances mocks base method
func (m *MockRepository) GetAccountBalances(arg0, arg1 string) ([]tb.TokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalances", arg0, arg1)
	ret0, _ := ret[0].([]tb.TokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalances indicates an expected call of GetAccountBalances
func (mr *MockRepositoryMockRecorder) GetAccountBalances(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalances", reflect.TypeOf((*MockRepository)(nil).GetAccountBalances), arg0, arg1)
}

// Update mocks base method
func (m *MockRepository) Update(updates []*tb.TokenBalance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockRepositoryMockRecorder) Update(updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), updates)
}

// GetHolders mocks base method
func (m *MockRepository) GetHolders(network, contract string, tokenID int64) ([]tb.TokenBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHolders", network, contract, tokenID)
	ret0, _ := ret[0].([]tb.TokenBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHolders indicates an expected call of GetHolders
func (mr *MockRepositoryMockRecorder) GetHolders(network, contract, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHolders", reflect.TypeOf((*MockRepository)(nil).GetHolders), network, contract, tokenID)
}

// BurnNft mocks base method
func (m *MockRepository) BurnNft(network, contract string, tokenID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BurnNft", network, contract, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BurnNft indicates an expected call of BurnNft
func (mr *MockRepositoryMockRecorder) BurnNft(network, contract, tokenID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BurnNft", reflect.TypeOf((*MockRepository)(nil).BurnNft), network, contract, tokenID)
}
