package consts

// Primitives
const (
	OR                 = "or"
	PAIR               = "pair"
	LAMBDA             = "lambda"
	CONTRACT           = "contract"
	OPTION             = "option"
	ADDRESS            = "address"
	NAT                = "nat"
	STRING             = "string"
	UNIT               = "unit"
	PARAMETER          = "parameter"
	STORAGE            = "storage"
	CODE               = "code"
	CREATECONTRACT     = "create_contract"
	SETDELEGATE        = "set_delegate"
	CHECKSIGNATURE     = "check_signature"
	CHAINID            = "chain_id"
	MAP                = "map"
	BIGMAP             = "big_map"
	SOME               = "some"
	LEFT               = "left"
	RIGHT              = "right"
	IF                 = "if"
	SET                = "set"
	LIST               = "list"
	KEY                = "key"
	SIGNATURE          = "signature"
	OPERATION          = "operation"
	INT                = "int"
	BYTES              = "bytes"
	MUTEZ              = "mutez"
	BOOL               = "bool"
	KEYHASH            = "key_hash"
	TIMESTAMP          = "timestamp"
	PUSH               = "push"
	ELT                = "elt"
	NONE               = "none"
	CAST               = "cast"
	RENAME             = "rename"
	SAPLINGTRANSACTION = "sapling_transaction"
	BAKERHASH          = "baker_hash"
	SAPLINGSTATE       = "sapling_state"
	NEVER              = "never"
	BLS12381FR         = "bls12_381_fr"
	BLS12381G1         = "bls12_381_g1"
	BLS12381G2         = "bls12_381_g2"
	TICKET             = "ticket"
)

// Data instructions
const (
	Pair  = "Pair"
	Some  = "Some"
	None  = "None"
	False = "False"
	True  = "True"
	Elt   = "Elt"
	Left  = "Left"
	Right = "Right"
	Unit  = "Unit"
)
