// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../mock/operation/mock.go -package=operation -typed
//

// Package operation is a generated GoMock package.
package operation

import (
	context "context"
	reflect "reflect"

	operation "github.com/baking-bad/bcdhub/internal/models/operation"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByHash mocks base method.
func (m *MockRepository) GetByHash(ctx context.Context, hash []byte) ([]operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, hash)
	ret0, _ := ret[0].([]operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockRepositoryMockRecorder) GetByHash(ctx, hash any) *MockRepositoryGetByHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockRepository)(nil).GetByHash), ctx, hash)
	return &MockRepositoryGetByHashCall{Call: call}
}

// MockRepositoryGetByHashCall wrap *gomock.Call
type MockRepositoryGetByHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetByHashCall) Return(arg0 []operation.Operation, arg1 error) *MockRepositoryGetByHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetByHashCall) Do(f func(context.Context, []byte) ([]operation.Operation, error)) *MockRepositoryGetByHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetByHashCall) DoAndReturn(f func(context.Context, []byte) ([]operation.Operation, error)) *MockRepositoryGetByHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByHashAndCounter mocks base method.
func (m *MockRepository) GetByHashAndCounter(ctx context.Context, hash []byte, counter int64) ([]operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHashAndCounter", ctx, hash, counter)
	ret0, _ := ret[0].([]operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHashAndCounter indicates an expected call of GetByHashAndCounter.
func (mr *MockRepositoryMockRecorder) GetByHashAndCounter(ctx, hash, counter any) *MockRepositoryGetByHashAndCounterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHashAndCounter", reflect.TypeOf((*MockRepository)(nil).GetByHashAndCounter), ctx, hash, counter)
	return &MockRepositoryGetByHashAndCounterCall{Call: call}
}

// MockRepositoryGetByHashAndCounterCall wrap *gomock.Call
type MockRepositoryGetByHashAndCounterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetByHashAndCounterCall) Return(arg0 []operation.Operation, arg1 error) *MockRepositoryGetByHashAndCounterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetByHashAndCounterCall) Do(f func(context.Context, []byte, int64) ([]operation.Operation, error)) *MockRepositoryGetByHashAndCounterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetByHashAndCounterCall) DoAndReturn(f func(context.Context, []byte, int64) ([]operation.Operation, error)) *MockRepositoryGetByHashAndCounterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int64) (operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *MockRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
	return &MockRepositoryGetByIDCall{Call: call}
}

// MockRepositoryGetByIDCall wrap *gomock.Call
type MockRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetByIDCall) Return(arg0 operation.Operation, arg1 error) *MockRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetByIDCall) Do(f func(context.Context, int64) (operation.Operation, error)) *MockRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetByIDCall) DoAndReturn(f func(context.Context, int64) (operation.Operation, error)) *MockRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Last mocks base method.
func (m *MockRepository) Last(ctx context.Context, filter map[string]any, lastID int64) (operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Last", ctx, filter, lastID)
	ret0, _ := ret[0].(operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Last indicates an expected call of Last.
func (mr *MockRepositoryMockRecorder) Last(ctx, filter, lastID any) *MockRepositoryLastCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Last", reflect.TypeOf((*MockRepository)(nil).Last), ctx, filter, lastID)
	return &MockRepositoryLastCall{Call: call}
}

// MockRepositoryLastCall wrap *gomock.Call
type MockRepositoryLastCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryLastCall) Return(arg0 operation.Operation, arg1 error) *MockRepositoryLastCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryLastCall) Do(f func(context.Context, map[string]any, int64) (operation.Operation, error)) *MockRepositoryLastCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryLastCall) DoAndReturn(f func(context.Context, map[string]any, int64) (operation.Operation, error)) *MockRepositoryLastCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListEvents mocks base method.
func (m *MockRepository) ListEvents(ctx context.Context, accountID, size, offset int64) ([]operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, accountID, size, offset)
	ret0, _ := ret[0].([]operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockRepositoryMockRecorder) ListEvents(ctx, accountID, size, offset any) *MockRepositoryListEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockRepository)(nil).ListEvents), ctx, accountID, size, offset)
	return &MockRepositoryListEventsCall{Call: call}
}

// MockRepositoryListEventsCall wrap *gomock.Call
type MockRepositoryListEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListEventsCall) Return(arg0 []operation.Operation, arg1 error) *MockRepositoryListEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListEventsCall) Do(f func(context.Context, int64, int64, int64) ([]operation.Operation, error)) *MockRepositoryListEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListEventsCall) DoAndReturn(f func(context.Context, int64, int64, int64) ([]operation.Operation, error)) *MockRepositoryListEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OPG mocks base method.
func (m *MockRepository) OPG(ctx context.Context, address string, size, lastID int64) ([]operation.OPG, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OPG", ctx, address, size, lastID)
	ret0, _ := ret[0].([]operation.OPG)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OPG indicates an expected call of OPG.
func (mr *MockRepositoryMockRecorder) OPG(ctx, address, size, lastID any) *MockRepositoryOPGCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OPG", reflect.TypeOf((*MockRepository)(nil).OPG), ctx, address, size, lastID)
	return &MockRepositoryOPGCall{Call: call}
}

// MockRepositoryOPGCall wrap *gomock.Call
type MockRepositoryOPGCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryOPGCall) Return(arg0 []operation.OPG, arg1 error) *MockRepositoryOPGCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryOPGCall) Do(f func(context.Context, string, int64, int64) ([]operation.OPG, error)) *MockRepositoryOPGCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryOPGCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]operation.OPG, error)) *MockRepositoryOPGCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Origination mocks base method.
func (m *MockRepository) Origination(ctx context.Context, accountID int64) (operation.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Origination", ctx, accountID)
	ret0, _ := ret[0].(operation.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Origination indicates an expected call of Origination.
func (mr *MockRepositoryMockRecorder) Origination(ctx, accountID any) *MockRepositoryOriginationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Origination", reflect.TypeOf((*MockRepository)(nil).Origination), ctx, accountID)
	return &MockRepositoryOriginationCall{Call: call}
}

// MockRepositoryOriginationCall wrap *gomock.Call
type MockRepositoryOriginationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryOriginationCall) Return(arg0 operation.Operation, arg1 error) *MockRepositoryOriginationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryOriginationCall) Do(f func(context.Context, int64) (operation.Operation, error)) *MockRepositoryOriginationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryOriginationCall) DoAndReturn(f func(context.Context, int64) (operation.Operation, error)) *MockRepositoryOriginationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
