rpc:
  mainnet:
    uri: ${MAINNET_RPC_URI:-https://michelson.etherlink.mainnet.octez.io}
    timeout: 20
    requests_per_second: 10
  shadownet:
    uri: https://michelson.etherlink.shadownet.octez.io
    timeout: 20
    requests_per_second: 20
  previewnet:
    uri: https://michelson.previewnet.tezosx.nomadic-labs.com
    timeout: 20
    requests_per_second: 20

log_level: ${LOG_LEVEL:-info}

services:
  mainnet:
  shadownet:
  previewnet:

storage:
  pg:
    host: ${DB_HOSTNAME:-db}
    port: 5432
    user: ${POSTGRES_USER}
    dbname: ${POSTGRES_DB:-bcd}
    password: ${POSTGRES_PASSWORD}
    sslmode: disable
  timeout: 10
  log_queries: ${POSTGRES_LOG_QUERIES:-false}

sentry:
  environment: production
  uri: ${SENTRY_DSN}
  front_uri: ${SENTRY_DSN_FRONT}
  debug: false

share_path: /etc/bcd

base_url: https://tezosx.better-call.dev

profiler:
  server: ${PROFILER_SERVER_ADDRESS:-http://127.0.0.1:4040}

api:
  project_name: api
  bind: ":14000"
  cors_enabled: false
  sentry_enabled: true
  seed_enabled: false
  page_size: ${PAGE_SIZE:-10}
  frontend:
    ga_enabled: true
    sandbox_mode: false
    rpc:
      mainnet: https://michelson.etherlink.mainnet.octez.io
      shadownet: https://michelson.etherlink.shadownet.octez.io
      previewnet: https://michelson.previewnet.tezosx.nomadic-labs.com
  networks:
    - mainnet
    - shadownet
    - previewnet

indexer:
  project_name: indexer
  sentry_enabled: true
  networks:
    mainnet:
      receiver_threads: ${MAINNET_THREADS:-10}
      start_level: ${TEZOSX_MAINNET_START_LEVEL:-51484839}
    shadownet:
      receiver_threads: ${TESTNET_THREADS:-10}
      start_level: ${TEZOSX_SHADOWNET_START_LEVEL:-6038916}
    previewnet:
      receiver_threads: ${TESTNET_THREADS:-10}
      start_level: ${TEZOSX_PREVIEWNET_START_LEVEL:-10}

scripts:
  aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  networks:
    - mainnet
    - shadownet
    - previewnet

implicit_contracts:
  mainnet:
    - address: "KT18oDJJKXMKhfE1bSuAPGp92pYcwVDiqsPw"
      level: ${TEZOSX_MAINNET_START_LEVEL:-51484839}
  shadownet:
    - address: "KT18oDJJKXMKhfE1bSuAPGp92pYcwVDiqsPw"
      level: ${TEZOSX_SHADOWNET_START_LEVEL:-6038916}
  previewnet:
    - address: "KT18oDJJKXMKhfE1bSuAPGp92pYcwVDiqsPw"
      level: ${TEZOSX_PREVIEWNET_START_LEVEL:-10}
