// Code generated by MockGen. DO NOT EDIT.
// Source: internal/models/tzip/repository.go

// Package tzip is a generated GoMock package.
package tzip

import (
	types "github.com/baking-bad/bcdhub/internal/models/types"
	model "github.com/baking-bad/bcdhub/internal/models/tzip"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockRepository) Get(network types.Network, address string) (*model.TZIP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", network, address)
	ret0, _ := ret[0].(*model.TZIP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRepositoryMockRecorder) Get(network, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), network, address)
}

// GetWithEvents mocks base method
func (m *MockRepository) GetWithEvents(updatedAt uint64) ([]model.TZIP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithEvents", updatedAt)
	ret0, _ := ret[0].([]model.TZIP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithEvents indicates an expected call of GetWithEvents
func (mr *MockRepositoryMockRecorder) GetWithEvents(updatedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithEvents", reflect.TypeOf((*MockRepository)(nil).GetWithEvents), updatedAt)
}

// GetBySlug mocks base method
func (m *MockRepository) GetBySlug(slug string) (*model.TZIP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", slug)
	ret0, _ := ret[0].(*model.TZIP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug
func (mr *MockRepositoryMockRecorder) GetBySlug(slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockRepository)(nil).GetBySlug), slug)
}

// GetAliases mocks base method
func (m *MockRepository) GetAliases(network types.Network) ([]model.TZIP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAliases", network)
	ret0, _ := ret[0].([]model.TZIP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAliases indicates an expected call of GetAliases
func (mr *MockRepositoryMockRecorder) GetAliases(network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAliases", reflect.TypeOf((*MockRepository)(nil).GetAliases), network)
}

// Events mocks base method
func (m *MockRepository) Events(network types.Network, address string) (model.Events, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", network, address)
	ret0, _ := ret[0].(model.Events)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events
func (mr *MockRepositoryMockRecorder) Events(network, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockRepository)(nil).Events), network, address)
}
