package docstring

import (
	"encoding/json"
	"testing"

	"github.com/baking-bad/bcdhub/internal/contractparser/meta"
)

func TestGetDocEntrypoints(t *testing.T) {
	tests := []struct {
		name     string
		metadata meta.Metadata
		result   string
	}{
		{
			name: "mainnet/KT1VsSxSXUkgw6zkBGgUuDXXuJs9ToPqkrCg/VestedFunds4",
			metadata: meta.Metadata{
				"0":                 &meta.NodeMetadata{Prim: "or", Args: []string{"0/0"}, Type: "namedunion"},
				"0/0":               &meta.NodeMetadata{FieldName: "Action", Prim: "pair", Args: []string{"0/0/0", "0/0/1"}, Type: "namedtuple", Name: "Action"},
				"0/0/0":             &meta.NodeMetadata{FieldName: "action_input", Prim: "or", Args: []string{"0/0/0/0/0", "0/0/0/0/1/o", "0/0/0/1/0", "0/0/0/1/1/o"}, Type: "namedunion", Name: "action_input"},
				"0/0/0/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/0/0":         &meta.NodeMetadata{FieldName: "Transfer", Prim: "pair", Args: []string{"0/0/0/0/0/0", "0/0/0/0/0/1"}, Type: "namedtuple", Name: "Transfer"},
				"0/0/0/0/0/0":       &meta.NodeMetadata{FieldName: "dest", Prim: "contract", Parameter: "{\"prim\":\"unit\"}", Type: "contract", Name: "dest"},
				"0/0/0/0/0/1":       &meta.NodeMetadata{FieldName: "transfer_amount", Prim: "mutez", Type: "mutez", Name: "transfer_amount"},
				"0/0/0/0/1":         &meta.NodeMetadata{FieldName: "Set_pour", Prim: "option", Type: "option"},
				"0/0/0/0/1/o":       &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/0/0/1/o/0", "0/0/0/0/1/o/1"}, Type: "namedtuple", Name: "Set_pour"},
				"0/0/0/0/1/o/0":     &meta.NodeMetadata{FieldName: "pour_dest", Prim: "contract", Parameter: "{\"prim\":\"unit\"}", Type: "contract", Name: "pour_dest"},
				"0/0/0/0/1/o/1":     &meta.NodeMetadata{FieldName: "pour_authorizer", Prim: "key", Type: "key", Name: "pour_authorizer"},
				"0/0/0/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/1/0":         &meta.NodeMetadata{FieldName: "Set_keys", Prim: "pair", Args: []string{"0/0/0/1/0/0", "0/0/0/1/0/1"}, Type: "namedtuple", Name: "Set_keys"},
				"0/0/0/1/0/0":       &meta.NodeMetadata{FieldName: "key_groups", Prim: "list", Type: "list", Name: "key_groups"},
				"0/0/0/1/0/0/l":     &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/0/1/0/0/l/0", "0/0/0/1/0/0/l/1"}, Type: "namedtuple"},
				"0/0/0/1/0/0/l/0":   &meta.NodeMetadata{FieldName: "signatories", Prim: "list", Type: "list", Name: "signatories"},
				"0/0/0/1/0/0/l/0/l": &meta.NodeMetadata{Prim: "key", Type: "key"},
				"0/0/0/1/0/0/l/1":   &meta.NodeMetadata{FieldName: "group_threshold", Prim: "nat", Type: "nat", Name: "group_threshold"},
				"0/0/0/1/0/1":       &meta.NodeMetadata{FieldName: "overall_threshold", Prim: "nat", Type: "nat", Name: "overall_threshold"},
				"0/0/0/1/1":         &meta.NodeMetadata{FieldName: "Set_delegate", Prim: "option", Type: "option"},
				"0/0/0/1/1/o":       &meta.NodeMetadata{Prim: "key_hash", Type: "key_hash", Name: "Set_delegate"},
				"0/0/1":             &meta.NodeMetadata{FieldName: "signatures", Prim: "list", Type: "list", Name: "signatures"},
				"0/0/1/l":           &meta.NodeMetadata{Prim: "list", Type: "list"},
				"0/0/1/l/l":         &meta.NodeMetadata{Prim: "option", Type: "option"},
				"0/0/1/l/l/o":       &meta.NodeMetadata{Prim: "signature", Type: "signature"},
			},
			result: `[{"name":"Action","typedef":[{"name":"Action","type":"pair","args":[{"key":"action_input","value":"$action_input"},{"key":"signatures","value":"list(list(option(signature)))"}]},{"name":"action_input","type":"or","args":[{"key":"Transfer","value":"$Transfer"},{"key":"Set_pour","value":"option($Set_pour)"},{"key":"Set_keys","value":"$Set_keys"},{"key":"Set_delegate","value":"option(key_hash)"}]},{"name":"Transfer","type":"pair","args":[{"key":"dest","value":"contract(unit)"},{"key":"transfer_amount","value":"mutez"}]},{"name":"Set_pour","type":"pair","args":[{"key":"pour_dest","value":"contract(unit)"},{"key":"pour_authorizer","value":"key"}]},{"name":"Set_keys","type":"pair","args":[{"key":"key_groups","value":"list($key_groups_item)"},{"key":"overall_threshold","value":"nat"}]},{"name":"key_groups_item","type":"pair","args":[{"key":"signatories","value":"list(key)"},{"key":"group_threshold","value":"nat"}]}],"bin_path":"0/0"}]`,
		},
		{
			name: "mainnet/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/tzBTC",
			metadata: meta.Metadata{
				"0/0/1/1/1":                 &meta.NodeMetadata{FieldName: "getTotalMinted", Prim: "pair", Args: []string{"0/0/1/1/1/0", "0/0/1/1/1/1"}, Type: "tuple", Name: "getTotalMinted"},
				"0/1":                       &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1":                   &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/1/0/1/1":         &meta.NodeMetadata{TypeName: "operator", FieldName: "removeOperator", Prim: "address", Type: "address", Name: "removeOperator"},
				"0/1/1/1/1/0/0/1/0/0":       &meta.NodeMetadata{TypeName: "current", Prim: "nat", Type: "nat", Name: "current"},
				"0/1/1/1/1/0/1/0/1":         &meta.NodeMetadata{FieldName: "epwFinishUpgrade", Prim: "unit", Type: "unit", Name: "epwFinishUpgrade"},
				"0/1/1/1/1/1":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/1/0/0":               &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/1/0/0":                   &meta.NodeMetadata{FieldName: "getTotalBurned", Prim: "pair", Args: []string{"0/1/0/0/0", "0/1/0/0/1"}, Type: "tuple", Name: "getTotalBurned"},
				"0/1/1/1/1/0/0/0/1/1/0":     &meta.NodeMetadata{TypeName: "migrationScript", Prim: "lambda", Parameter: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", ReturnValue: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", Type: "lambda"},
				"0/1/1/1/1/0/0/0/1/1/1/1/o": &meta.NodeMetadata{Prim: "lambda", Parameter: "{\"prim\":\"pair\",\"args\":[{\"prim\":\"unit\"},{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}]}", ReturnValue: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", Type: "lambda"},
				"0/1/1/1/1/0/0/0/1/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/0/1/1/0/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/0/1/1/0/1/0":     &meta.NodeMetadata{TypeName: "to", Prim: "address", Type: "address", Name: "to"},
				"0/1/1/1/1/1/0/0/1":         &meta.NodeMetadata{TypeName: "value", FieldName: "burn", Prim: "nat", Type: "nat", Name: "burn"},
				"0/0/0/1/0":                 &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/0/0":                 &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/1/0/1/1":                 &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"address\"}", Type: "contract"},
				"0/1/1/1/1/0/0/0/0/1":       &meta.NodeMetadata{Prim: "bytes", Type: "bytes"},
				"0/1/1/1/1/1/1/0/0":         &meta.NodeMetadata{TypeName: "redeem", FieldName: "setRedeemAddress", Prim: "address", Type: "address", Name: "setRedeemAddress"},
				"0/1/1/1/1/0/0/0/1/1/1/0":   &meta.NodeMetadata{TypeName: "newCode", Prim: "option", Type: "option"},
				"0/1/1/1/1/1/1/1/1/0":       &meta.NodeMetadata{TypeName: "newOwner", FieldName: "transferOwnership", Prim: "address", Type: "address", Name: "transferOwnership"},
				"0/0/1/1/1/0":               &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/1/1/1/0/0":               &meta.NodeMetadata{Prim: "list", Type: "list"},
				"0/1/1/1/0/0/l":             &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/1/1/0/1":               &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"list\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"nat\"},{\"prim\":\"pair\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"pair\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"pair\",\"args\":[{\"prim\":\"nat\"},{\"prim\":\"map\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"string\"}]}]}]}]}]}]}", Type: "contract"},
				"0/1/1/1/1/0/0/0/0":         &meta.NodeMetadata{FieldName: "run", Prim: "pair", Args: []string{"0/1/1/1/1/0/0/0/0/0", "0/1/1/1/1/0/0/0/0/1"}, Type: "tuple", Name: "run"},
				"0/0/1/0/1":                 &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/0/1/1/1/1":               &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/1/1/0":                   &meta.NodeMetadata{FieldName: "getRedeemAddress", Prim: "pair", Args: []string{"0/1/1/0/0", "0/1/1/0/1"}, Type: "tuple", Name: "getRedeemAddress"},
				"0/1/1/1/1/0":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/0/0/1/1/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/0/1/1/0":         &meta.NodeMetadata{FieldName: "transfer", Prim: "pair", Args: []string{"0/1/1/1/1/0/1/1/0/0", "0/1/1/1/1/0/1/1/0/1/0", "0/1/1/1/1/0/1/1/0/1/1"}, Type: "namedtuple", Name: "transfer"},
				"0/1/1/1/1/1/0/0/0/1":       &meta.NodeMetadata{TypeName: "value", Prim: "nat", Type: "nat", Name: "value"},
				"0/1/1/1/1/1/1/0/1":         &meta.NodeMetadata{FieldName: "pause", Prim: "unit", Type: "unit", Name: "pause"},
				"0/0/0/1/0/0":               &meta.NodeMetadata{TypeName: "owner", Prim: "address", Type: "address", Name: "owner"},
				"0/0/1/0":                   &meta.NodeMetadata{FieldName: "getBalance", Prim: "pair", Args: []string{"0/0/1/0/0", "0/0/1/0/1"}, Type: "namedtuple", Name: "getBalance"},
				"0/1/0/1":                   &meta.NodeMetadata{FieldName: "getOwner", Prim: "pair", Args: []string{"0/1/0/1/0", "0/1/0/1/1"}, Type: "tuple", Name: "getOwner"},
				"0/1/1/1/1/0/0/0/1/0/0":     &meta.NodeMetadata{TypeName: "currentVersion", Prim: "nat", Type: "nat"},
				"0/1/0/1/0":                 &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/1/1/1/1/0/0/0/0/0":       &meta.NodeMetadata{Prim: "string", Type: "string"},
				"0/1/1/1/1/0/0/0/1/1/1/0/o": &meta.NodeMetadata{Prim: "lambda", Parameter: "{\"prim\":\"pair\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"bytes\"}]},{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}]}", ReturnValue: "{\"prim\": \"pair\",\"args\": [{\"prim\": \"list\",\"args\": [{\"prim\": \"operation\"}]},{\"prim\": \"big_map\",\"args\": [{\"prim\": \"bytes\"},{\"prim\": \"bytes\"}]}]", Type: "lambda"},
				"0/1/1/1/1/1/0/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/1":                   &meta.NodeMetadata{FieldName: "getAllowance", Prim: "pair", Args: []string{"0/0/0/1/0/0", "0/0/0/1/0/1", "0/0/0/1/1"}, Type: "namedtuple", Name: "getAllowance"},
				"0/0/0/1/1":                 &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/0/1/1":                   &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0":                     &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/1/1":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/0/0":                 &meta.NodeMetadata{TypeName: "owner", Prim: "address", Type: "address", Name: "owner"},
				"0/1/1/1/0":                 &meta.NodeMetadata{FieldName: "getTokenMetadata", Prim: "pair", Args: []string{"0/1/1/1/0/0", "0/1/1/1/0/1"}, Type: "tuple", Name: "getTokenMetadata"},
				"0/1/1/1/1":                 &meta.NodeMetadata{FieldName: "safeEntrypoints", Prim: "or", Type: "or"},
				"0/1/1/1/1/1/1/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/1/1/1/0":         &meta.NodeMetadata{FieldName: "unpause", Prim: "unit", Type: "unit", Name: "unpause"},
				"0/1/1/1/1/1/1/1/1":         &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0":                     &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/0/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/1/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/1/1/1/0":       &meta.NodeMetadata{TypeName: "spender", Prim: "address", Type: "address", Name: "spender"},
				"0/1/1/1/1/0/1/1/0/1/1":     &meta.NodeMetadata{TypeName: "value", Prim: "nat", Type: "nat", Name: "value"},
				"0/1/1/1/1/1/1/1/1/1":       &meta.NodeMetadata{FieldName: "acceptOwnership", Prim: "unit", Type: "unit", Name: "acceptOwnership"},
				"0/0":                       &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/1/0":                 &meta.NodeMetadata{FieldName: "getTotalSupply", Prim: "pair", Args: []string{"0/0/1/1/0/0", "0/0/1/1/0/1"}, Type: "tuple", Name: "getTotalSupply"},
				"0/1/1/1/1/0/0/1/0":         &meta.NodeMetadata{FieldName: "epwBeginUpgrade", Prim: "pair", Args: []string{"0/1/1/1/1/0/0/1/0/0", "0/1/1/1/1/0/0/1/0/1"}, Type: "namedtuple", Name: "epwBeginUpgrade"},
				"0/1/1/1/1/0/0/1/0/1":       &meta.NodeMetadata{TypeName: "new", Prim: "nat", Type: "nat", Name: "new"},
				"0/0/1/1/0/1":               &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/1/1/0/1":                 &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"address\"}", Type: "contract"},
				"0/1/1/1/1/0/0/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/1/1/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/0/0/1/0":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/0/1/1/0/0":       &meta.NodeMetadata{TypeName: "from", Prim: "address", Type: "address", Name: "from"},
				"0/1/1/1/1/1/0":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/1/0/0/0":         &meta.NodeMetadata{FieldName: "mint", Prim: "pair", Args: []string{"0/1/1/1/1/1/0/0/0/0", "0/1/1/1/1/1/0/0/0/1"}, Type: "namedtuple", Name: "mint"},
				"0/1/1/1/1/1/0/1/0":         &meta.NodeMetadata{TypeName: "operator", FieldName: "addOperator", Prim: "address", Type: "address", Name: "addOperator"},
				"0/1/0/0/1":                 &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/1/1/1/1/0/1":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/1/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/1/1/1/1":       &meta.NodeMetadata{TypeName: "value", Prim: "nat", Type: "nat", Name: "value"},
				"0/0/0/0":                   &meta.NodeMetadata{FieldName: "getVersion", Prim: "pair", Args: []string{"0/0/0/0/0", "0/0/0/0/1"}, Type: "tuple", Name: "getVersion"},
				"0/0/0/1/0/1":               &meta.NodeMetadata{TypeName: "spender", Prim: "address", Type: "address", Name: "spender"},
				"0/1/1/1/1/0/0/0/1":         &meta.NodeMetadata{FieldName: "upgrade", Prim: "pair", Args: []string{"0/1/1/1/1/0/0/0/1/0/0", "0/1/1/1/1/0/0/0/1/0/1", "0/1/1/1/1/0/0/0/1/1/0", "0/1/1/1/1/0/0/0/1/1/1/0/o", "0/1/1/1/1/0/0/0/1/1/1/1/o"}, Type: "tuple", Name: "upgrade"},
				"0/1/1/1/1/0/0/0/1/0/1":     &meta.NodeMetadata{TypeName: "newVersion", Prim: "nat", Type: "nat"},
				"0/1/1/1/1/0/1/0/0":         &meta.NodeMetadata{TypeName: "contractcode", FieldName: "epwSetCode", Prim: "lambda", Parameter: "{\"prim\":\"pair\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"bytes\"}]},{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}]}", ReturnValue: "{\"prim\": \"pair\",\"args\": [{\"prim\": \"list\",\"args\": [{\"prim\": \"operation\"}]},{\"prim\": \"big_map\",\"args\": [{\"prim\": \"bytes\"},{\"prim\": \"bytes\"}]}]", Type: "lambda", Name: "epwSetCode"},
				"0/1/1/1/1/1/0/0/0/0":       &meta.NodeMetadata{TypeName: "to", Prim: "address", Type: "address", Name: "to"},
				"0/1/1/1/1/1/0/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0":                         &meta.NodeMetadata{Prim: "or", Args: []string{"0/0/0/0", "0/0/0/1", "0/0/1/0", "0/0/1/1/0", "0/0/1/1/1", "0/1/0/0", "0/1/0/1", "0/1/1/0", "0/1/1/1/0", "0/1/1/1/1/0/0/0/0", "0/1/1/1/1/0/0/0/1", "0/1/1/1/1/0/0/1/0", "0/1/1/1/1/0/0/1/1", "0/1/1/1/1/0/1/0/0", "0/1/1/1/1/0/1/0/1", "0/1/1/1/1/0/1/1/0", "0/1/1/1/1/0/1/1/1", "0/1/1/1/1/1/0/0/0", "0/1/1/1/1/1/0/0/1", "0/1/1/1/1/1/0/1/0", "0/1/1/1/1/1/0/1/1", "0/1/1/1/1/1/1/0/0", "0/1/1/1/1/1/1/0/1", "0/1/1/1/1/1/1/1/0", "0/1/1/1/1/1/1/1/1/0", "0/1/1/1/1/1/1/1/1/1"}, Type: "namedunion"},
				"0/0/0/0/1":                 &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/1/1/1/1/0/0/0/1/1/1/1":   &meta.NodeMetadata{TypeName: "newPermCode", Prim: "option", Type: "option"},
				"0/1/1/1/1/0/0/1/1":         &meta.NodeMetadata{TypeName: "migrationscript", FieldName: "epwApplyMigration", Prim: "lambda", Parameter: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", ReturnValue: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", Type: "lambda", Name: "epwApplyMigration"},
				"0/1/1/1/1/0/0":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/1/1/1":         &meta.NodeMetadata{FieldName: "approve", Prim: "pair", Args: []string{"0/1/1/1/1/0/1/1/1/0", "0/1/1/1/1/0/1/1/1/1"}, Type: "namedtuple", Name: "approve"},
				"0/0/0/0/0":                 &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/0/1":                     &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1":                     &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/0/0":                 &meta.NodeMetadata{Prim: "unit", Type: "unit"},
			},
			result: `[{"name":"getVersion","typedef":[{"name":"getVersion","type":"pair","args":[{"value":"unit"},{"value":"contract(nat)"}]}],"bin_path":"0/0/0/0"},{"name":"getAllowance","typedef":[{"name":"getAllowance","type":"pair","args":[{"key":"owner","value":"address"},{"key":"spender","value":"address"},{"value":"contract(nat)"}]}],"bin_path":"0/0/0/1"},{"name":"getBalance","typedef":[{"name":"getBalance","type":"pair","args":[{"key":"owner","value":"address"},{"value":"contract(nat)"}]}],"bin_path":"0/0/1/0"},{"name":"getTotalSupply","typedef":[{"name":"getTotalSupply","type":"pair","args":[{"value":"unit"},{"value":"contract(nat)"}]}],"bin_path":"0/0/1/1/0"},{"name":"getTotalMinted","typedef":[{"name":"getTotalMinted","type":"pair","args":[{"value":"unit"},{"value":"contract(nat)"}]}],"bin_path":"0/0/1/1/1"},{"name":"getTotalBurned","typedef":[{"name":"getTotalBurned","type":"pair","args":[{"value":"unit"},{"value":"contract(nat)"}]}],"bin_path":"0/1/0/0"},{"name":"getOwner","typedef":[{"name":"getOwner","type":"pair","args":[{"value":"unit"},{"value":"contract(address)"}]}],"bin_path":"0/1/0/1"},{"name":"getRedeemAddress","typedef":[{"name":"getRedeemAddress","type":"pair","args":[{"value":"unit"},{"value":"contract(address)"}]}],"bin_path":"0/1/1/0"},{"name":"getTokenMetadata","typedef":[{"name":"getTokenMetadata","type":"pair","args":[{"value":"list(nat)"},{"value":"contract($contract0_param)"}]},{"name":"contract0_param","type":"list (pair nat (pair string (pair string (pair nat (map string string)))))"}],"bin_path":"0/1/1/1/0"},{"name":"run","typedef":[{"name":"run","type":"pair(string, bytes)"}],"bin_path":"0/1/1/1/1/0/0/0/0"},{"name":"upgrade","typedef":[{"name":"upgrade","type":"pair","args":[{"value":"nat"},{"value":"nat"},{"value":"$lambda0"},{"value":"option($lambda1)"},{"value":"option($lambda2)"}]},{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"big_map bytes bytes"},{"key":"return","value":"big_map bytes bytes"}]},{"name":"lambda1","type":"lambda","args":[{"key":"input","value":"pair (pair string bytes) (big_map bytes bytes)"},{"key":"return","value":"pair (list operation) (big_map bytes bytes)"}]},{"name":"lambda2","type":"lambda","args":[{"key":"input","value":"pair unit (big_map bytes bytes)"},{"key":"return","value":"big_map bytes bytes"}]}],"bin_path":"0/1/1/1/1/0/0/0/1"},{"name":"epwBeginUpgrade","typedef":[{"name":"epwBeginUpgrade","type":"pair","args":[{"key":"current","value":"nat"},{"key":"new","value":"nat"}]}],"bin_path":"0/1/1/1/1/0/0/1/0"},{"name":"epwApplyMigration","typedef":[{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"big_map bytes bytes"},{"key":"return","value":"big_map bytes bytes"}]}],"bin_path":"0/1/1/1/1/0/0/1/1"},{"name":"epwSetCode","typedef":[{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"pair (pair string bytes) (big_map bytes bytes)"},{"key":"return","value":"pair (list operation) (big_map bytes bytes)"}]}],"bin_path":"0/1/1/1/1/0/1/0/0"},{"name":"epwFinishUpgrade","typedef":[{"name":"epwFinishUpgrade","type":"unit"}],"bin_path":"0/1/1/1/1/0/1/0/1"},{"name":"transfer","typedef":[{"name":"transfer","type":"pair","args":[{"key":"from","value":"address"},{"key":"to","value":"address"},{"key":"value","value":"nat"}]}],"bin_path":"0/1/1/1/1/0/1/1/0"},{"name":"approve","typedef":[{"name":"approve","type":"pair","args":[{"key":"spender","value":"address"},{"key":"value","value":"nat"}]}],"bin_path":"0/1/1/1/1/0/1/1/1"},{"name":"mint","typedef":[{"name":"mint","type":"pair","args":[{"key":"to","value":"address"},{"key":"value","value":"nat"}]}],"bin_path":"0/1/1/1/1/1/0/0/0"},{"name":"burn","typedef":[{"name":"burn","type":"nat"}],"bin_path":"0/1/1/1/1/1/0/0/1"},{"name":"addOperator","typedef":[{"name":"addOperator","type":"address"}],"bin_path":"0/1/1/1/1/1/0/1/0"},{"name":"removeOperator","typedef":[{"name":"removeOperator","type":"address"}],"bin_path":"0/1/1/1/1/1/0/1/1"},{"name":"setRedeemAddress","typedef":[{"name":"setRedeemAddress","type":"address"}],"bin_path":"0/1/1/1/1/1/1/0/0"},{"name":"pause","typedef":[{"name":"pause","type":"unit"}],"bin_path":"0/1/1/1/1/1/1/0/1"},{"name":"unpause","typedef":[{"name":"unpause","type":"unit"}],"bin_path":"0/1/1/1/1/1/1/1/0"},{"name":"transferOwnership","typedef":[{"name":"transferOwnership","type":"address"}],"bin_path":"0/1/1/1/1/1/1/1/1/0"},{"name":"acceptOwnership","typedef":[{"name":"acceptOwnership","type":"unit"}],"bin_path":"0/1/1/1/1/1/1/1/1/1"}]`,
		},
		{
			name: "mainnet/KT1U1JZaXoG4u1EPnhHL4R4otzkWc1L34q3c/Equisafe-KYC-registrar",
			metadata: meta.Metadata{
				"0":                 &meta.NodeMetadata{Prim: "or", Args: []string{"0/0/0", "0/0/1", "0/1/0", "0/1/1"}, Type: "namedunion"},
				"0/0":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0":             &meta.NodeMetadata{FieldName: "addMembers", Prim: "list", Type: "list", Name: "addMembers"},
				"0/0/0/l":           &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/0/l/0", "0/0/0/l/1"}, Type: "namedtuple"},
				"0/0/0/l/0":         &meta.NodeMetadata{FieldName: "0", Prim: "address", Type: "address", Name: "0"},
				"0/0/0/l/1":         &meta.NodeMetadata{FieldName: "1", Prim: "pair", Args: []string{"0/0/0/l/1/0/0/0", "0/0/0/l/1/0/0/1", "0/0/0/l/1/0/1/0", "0/0/0/l/1/0/1/1", "0/0/0/l/1/1"}, Type: "namedtuple", Name: "1"},
				"0/0/0/l/1/0":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/l/1/0/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/l/1/0/0/0":   &meta.NodeMetadata{FieldName: "country", Prim: "nat", Type: "nat", Name: "country"},
				"0/0/0/l/1/0/0/1":   &meta.NodeMetadata{FieldName: "expires", Prim: "timestamp", Type: "timestamp", Name: "expires"},
				"0/0/0/l/1/0/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/l/1/0/1/0":   &meta.NodeMetadata{FieldName: "rating", Prim: "nat", Type: "nat", Name: "rating"},
				"0/0/0/l/1/0/1/1":   &meta.NodeMetadata{FieldName: "region", Prim: "nat", Type: "nat", Name: "region"},
				"0/0/0/l/1/1":       &meta.NodeMetadata{FieldName: "restricted", Prim: "bool", Type: "bool", Name: "restricted"},
				"0/0/1":             &meta.NodeMetadata{FieldName: "checkMember", Prim: "pair", Args: []string{"0/0/1/0/0", "0/0/1/0/1", "0/0/1/1"}, Type: "namedtuple", Name: "checkMember"},
				"0/0/1/0":           &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/0":         &meta.NodeMetadata{FieldName: "0", Prim: "address", Type: "address", Name: "0"},
				"0/0/1/0/1":         &meta.NodeMetadata{FieldName: "1", Prim: "map", Type: "map", Name: "1"},
				"0/0/1/0/1/k":       &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/0/1/0/1/v":       &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/1/0/1/v/0/0", "0/0/1/0/1/v/0/1", "0/0/1/0/1/v/1/0", "0/0/1/0/1/v/1/1"}, Type: "namedtuple"},
				"0/0/1/0/1/v/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/1/v/0/0":   &meta.NodeMetadata{FieldName: "country_invest_limit", Prim: "nat", Type: "nat", Name: "country_invest_limit"},
				"0/0/1/0/1/v/0/1":   &meta.NodeMetadata{FieldName: "min_rating", Prim: "nat", Type: "nat", Name: "min_rating"},
				"0/0/1/0/1/v/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/1/v/1/0":   &meta.NodeMetadata{FieldName: "rating_restrictions", Prim: "map", Type: "map", Name: "rating_restrictions"},
				"0/0/1/0/1/v/1/0/k": &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/0/1/0/1/v/1/0/v": &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/0/1/0/1/v/1/1":   &meta.NodeMetadata{FieldName: "vesting", Prim: "timestamp", Type: "timestamp", Name: "vesting"},
				"0/0/1/1":           &meta.NodeMetadata{FieldName: "2", Prim: "bool", Type: "bool", Name: "2"},
				"0/1":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0":             &meta.NodeMetadata{FieldName: "getMember", Prim: "pair", Args: []string{"0/1/0/0", "0/1/0/1"}, Type: "namedtuple", Name: "getMember"},
				"0/1/0/0":           &meta.NodeMetadata{FieldName: "0", Prim: "address", Type: "address", Name: "0"},
				"0/1/0/1":           &meta.NodeMetadata{FieldName: "1", Prim: "lambda", Parameter: "{\"prim\":\"pair\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"nat\",\"annots\":[\"%country\"]},{\"prim\":\"timestamp\",\"annots\":[\"%expires\"]}]},{\"prim\":\"pair\",\"args\":[{\"prim\":\"nat\",\"annots\":[\"%rating\"]},{\"prim\":\"nat\",\"annots\":[\"%region\"]}]}]},{\"prim\":\"bool\",\"annots\":[\"%restricted\"]}]}", Type: "lambda", Name: "1"},
				"0/1/1":             &meta.NodeMetadata{FieldName: "removeMembers", Prim: "list", Type: "list", Name: "removeMembers"},
				"0/1/1/l":           &meta.NodeMetadata{Prim: "address", Type: "address"},
			},
			result: `[{"name":"addMembers","typedef":[{"name":"addMembers","type":"list($addMembers_item)"},{"name":"addMembers_item","type":"pair","args":[{"key":"0","value":"address"},{"key":"1","value":"$1"}]},{"name":"1","type":"pair","args":[{"key":"country","value":"nat"},{"key":"expires","value":"timestamp"},{"key":"rating","value":"nat"},{"key":"region","value":"nat"},{"key":"restricted","value":"bool"}]}],"bin_path":"0/0/0"},{"name":"checkMember","typedef":[{"name":"checkMember","type":"pair","args":[{"key":"0","value":"address"},{"key":"1","value":"$1"},{"key":"2","value":"bool"}]},{"name":"1","type":"map","args":[{"key":"key","value":"nat"},{"key":"value","value":"$1_value"}]},{"name":"1_value","type":"pair","args":[{"key":"country_invest_limit","value":"nat"},{"key":"min_rating","value":"nat"},{"key":"rating_restrictions","value":"map(nat, nat)"},{"key":"vesting","value":"timestamp"}]}],"bin_path":"0/0/1"},{"name":"getMember","typedef":[{"name":"getMember","type":"pair","args":[{"key":"0","value":"address"},{"key":"1","value":"$lambda0"}]},{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"pair (pair (pair (nat %country) (timestamp %expires)) (pair (nat %rating) (nat %region))) (bool %restricted)"},{"key":"return","value":""}]}],"bin_path":"0/1/0"},{"name":"removeMembers","typedef":[{"name":"removeMembers","type":"list(address)"}],"bin_path":"0/1/1"}]`,
		},
		{
			name: "mainnet/KT1ChNsEFxwyCbJyWGSL3KdjeXE28AY1Kaog/BakersRegistry",
			metadata: meta.Metadata{
				"0":                     &meta.NodeMetadata{Prim: "or", Args: []string{"0/0", "0/1/0", "0/1/1"}, Type: "namedunion"},
				"0/0":                   &meta.NodeMetadata{FieldName: "set_data", Prim: "pair", Args: []string{"0/0/0", "0/0/1/0/o", "0/0/1/1/o"}, Type: "namedtuple", Name: "set_data"},
				"0/0/0":                 &meta.NodeMetadata{FieldName: "delegate", Prim: "key_hash", Type: "key_hash", Name: "delegate"},
				"0/0/1":                 &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0":               &meta.NodeMetadata{FieldName: "data", Prim: "option", Type: "option"},
				"0/0/1/0/o":             &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/1/0/o/0/0/0", "0/0/1/0/o/0/0/1", "0/0/1/0/o/0/1", "0/0/1/0/o/1/0/0", "0/0/1/0/o/1/0/1", "0/0/1/0/o/1/1/0/0/0", "0/0/1/0/o/1/1/0/0/1", "0/0/1/0/o/1/1/0/1/0", "0/0/1/0/o/1/1/0/1/1/0", "0/0/1/0/o/1/1/0/1/1/1", "0/0/1/0/o/1/1/1/0/0", "0/0/1/0/o/1/1/1/0/1", "0/0/1/0/o/1/1/1/1/0", "0/0/1/0/o/1/1/1/1/1"}, Type: "namedtuple", Name: "data"},
				"0/0/1/0/o/0":           &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/0/0":         &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/0/0/0":       &meta.NodeMetadata{FieldName: "bakerName", Prim: "bytes", Type: "bytes", Name: "bakerName"},
				"0/0/1/0/o/0/0/1":       &meta.NodeMetadata{FieldName: "openForDelegation", Prim: "bool", Type: "bool", Name: "openForDelegation"},
				"0/0/1/0/o/0/1":         &meta.NodeMetadata{FieldName: "bakerOffchainRegistryUrl", Prim: "bytes", Type: "bytes", Name: "bakerOffchainRegistryUrl"},
				"0/0/1/0/o/1":           &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/0":         &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/0/0":       &meta.NodeMetadata{FieldName: "split", Prim: "nat", Type: "nat", Name: "split"},
				"0/0/1/0/o/1/0/1":       &meta.NodeMetadata{FieldName: "bakerPaysFromAccounts", Prim: "list", Type: "list", Name: "bakerPaysFromAccounts"},
				"0/0/1/0/o/1/0/1/l":     &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/0/1/0/o/1/1":         &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/0":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/0/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/0/0/0":   &meta.NodeMetadata{FieldName: "minDelegation", Prim: "nat", Type: "nat", Name: "minDelegation"},
				"0/0/1/0/o/1/1/0/0/1":   &meta.NodeMetadata{FieldName: "subtractPayoutsLessThanMin", Prim: "bool", Type: "bool", Name: "subtractPayoutsLessThanMin"},
				"0/0/1/0/o/1/1/0/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/0/1/0":   &meta.NodeMetadata{FieldName: "payoutDelay", Prim: "int", Type: "int", Name: "payoutDelay"},
				"0/0/1/0/o/1/1/0/1/1":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/0/1/1/0": &meta.NodeMetadata{FieldName: "payoutFrequency", Prim: "nat", Type: "nat", Name: "payoutFrequency"},
				"0/0/1/0/o/1/1/0/1/1/1": &meta.NodeMetadata{FieldName: "minPayout", Prim: "int", Type: "int", Name: "minPayout"},
				"0/0/1/0/o/1/1/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/1/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/1/0/0":   &meta.NodeMetadata{FieldName: "bakerChargesTransactionFee", Prim: "bool", Type: "bool", Name: "bakerChargesTransactionFee"},
				"0/0/1/0/o/1/1/1/0/1":   &meta.NodeMetadata{FieldName: "paymentConfigMask", Prim: "nat", Type: "nat", Name: "paymentConfigMask"},
				"0/0/1/0/o/1/1/1/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/0/o/1/1/1/1/0":   &meta.NodeMetadata{FieldName: "overDelegationThreshold", Prim: "nat", Type: "nat", Name: "overDelegationThreshold"},
				"0/0/1/0/o/1/1/1/1/1":   &meta.NodeMetadata{FieldName: "subtractRewardsFromUninvitedDelegation", Prim: "bool", Type: "bool", Name: "subtractRewardsFromUninvitedDelegation"},
				"0/0/1/1":               &meta.NodeMetadata{FieldName: "reporterAccount", Prim: "option", Type: "option"},
				"0/0/1/1/o":             &meta.NodeMetadata{Prim: "address", Type: "address", Name: "reporterAccount"},
				"0/1":                   &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0":                 &meta.NodeMetadata{FieldName: "set_fees", Prim: "pair", Args: []string{"0/1/0/0", "0/1/0/1"}, Type: "namedtuple", Name: "set_fees"},
				"0/1/0/0":               &meta.NodeMetadata{FieldName: "signup_fee", Prim: "mutez", Type: "mutez", Name: "signup_fee"},
				"0/1/0/1":               &meta.NodeMetadata{FieldName: "update_fee", Prim: "mutez", Type: "mutez", Name: "update_fee"},
				"0/1/1":                 &meta.NodeMetadata{FieldName: "withdraw", Prim: "contract", Parameter: "{\"prim\":\"unit\"}", Type: "contract", Name: "withdraw"},
			},
			result: `[{"name":"set_data","typedef":[{"name":"set_data","type":"pair","args":[{"key":"delegate","value":"key_hash"},{"key":"data","value":"option($data)"},{"key":"reporterAccount","value":"option(address)"}]},{"name":"data","type":"pair","args":[{"key":"bakerName","value":"bytes"},{"key":"openForDelegation","value":"bool"},{"key":"bakerOffchainRegistryUrl","value":"bytes"},{"key":"split","value":"nat"},{"key":"bakerPaysFromAccounts","value":"list(address)"},{"key":"minDelegation","value":"nat"},{"key":"subtractPayoutsLessThanMin","value":"bool"},{"key":"payoutDelay","value":"int"},{"key":"payoutFrequency","value":"nat"},{"key":"minPayout","value":"int"},{"key":"bakerChargesTransactionFee","value":"bool"},{"key":"paymentConfigMask","value":"nat"},{"key":"overDelegationThreshold","value":"nat"},{"key":"subtractRewardsFromUninvitedDelegation","value":"bool"}]}],"bin_path":"0/0"},{"name":"set_fees","typedef":[{"name":"set_fees","type":"pair","args":[{"key":"signup_fee","value":"mutez"},{"key":"update_fee","value":"mutez"}]}],"bin_path":"0/1/0"},{"name":"withdraw","typedef":[{"name":"withdraw","type":"contract(unit)"}],"bin_path":"0/1/1"}]`,
		},
		{
			name: "carthagenet/KT1S1YSgff244zEPbuoyY2CPQbVm12pxg2em/entrypoint_#",
			metadata: meta.Metadata{
				"0":           &meta.NodeMetadata{Prim: "or", Args: []string{"0/0/0/0", "0/0/0/1", "0/0/1/0", "0/0/1/1", "0/1/0/0", "0/1/0/1", "0/1/1/0", "0/1/1/1"}, Type: "union"},
				"0/0":         &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0":       &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/0":     &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/0/0/0", "0/0/0/0/1"}, Type: "tuple"},
				"0/0/0/0/0":   &meta.NodeMetadata{Prim: "string", Type: "string"},
				"0/0/0/0/1":   &meta.NodeMetadata{Prim: "bytes", Type: "bytes"},
				"0/0/0/1":     &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/0/1/0", "0/0/0/1/1/0", "0/0/0/1/1/1"}, Type: "tuple"},
				"0/0/0/1/0":   &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/0/0/1/1":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/1/0": &meta.NodeMetadata{Prim: "lambda", Parameter: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", Type: "lambda"},
				"0/0/0/1/1/1": &meta.NodeMetadata{Prim: "lambda", Parameter: "{\"prim\":\"pair\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"bytes\"}]},{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}]}", Type: "lambda"},
				"0/0/1":       &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/0":     &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/1/0/0", "0/0/1/0/1"}, Type: "tuple"},
				"0/0/1/0/0":   &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/0/1/0/1":   &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"nat\"}", Type: "contract"},
				"0/0/1/1":     &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1":         &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0":       &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0/0":     &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/0/1":     &meta.NodeMetadata{Prim: "lambda", Parameter: "{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}", Type: "lambda"},
				"0/1/1":       &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/0":     &meta.NodeMetadata{Prim: "lambda", Parameter: "{\"prim\":\"pair\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"string\"},{\"prim\":\"bytes\"}]},{\"prim\":\"big_map\",\"args\":[{\"prim\":\"bytes\"},{\"prim\":\"bytes\"}]}]}", Type: "lambda"},
				"0/1/1/1":     &meta.NodeMetadata{Prim: "unit", Type: "unit"},
			},
			result: `[{"name":"entrypoint_0","typedef":[{"name":"entrypoint_0","type":"pair(string, bytes)"}],"bin_path":"0/0/0/0"},{"name":"entrypoint_1","typedef":[{"name":"entrypoint_1","type":"pair","args":[{"value":"nat"},{"value":"$lambda0"},{"value":"$lambda1"}]},{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"big_map bytes bytes"},{"key":"return","value":""}]},{"name":"lambda1","type":"lambda","args":[{"key":"input","value":"pair (pair string bytes) (big_map bytes bytes)"},{"key":"return","value":""}]}],"bin_path":"0/0/0/1"},{"name":"entrypoint_2","typedef":[{"name":"entrypoint_2","type":"pair","args":[{"value":"unit"},{"value":"contract(nat)"}]}],"bin_path":"0/0/1/0"},{"name":"entrypoint_3","typedef":[{"name":"entrypoint_3","type":"address"}],"bin_path":"0/0/1/1"},{"name":"entrypoint_4","typedef":[{"name":"entrypoint_4","type":"nat"}],"bin_path":"0/1/0/0"},{"name":"entrypoint_5","typedef":[{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"big_map bytes bytes"},{"key":"return","value":""}]}],"bin_path":"0/1/0/1"},{"name":"entrypoint_6","typedef":[{"name":"lambda0","type":"lambda","args":[{"key":"input","value":"pair (pair string bytes) (big_map bytes bytes)"},{"key":"return","value":""}]}],"bin_path":"0/1/1/0"},{"name":"entrypoint_7","typedef":[{"name":"entrypoint_7","type":"unit"}],"bin_path":"0/1/1/1"}]`,
		},
		{
			name: "carthagenet/KT19jHRkd5d7ugUGYg78RsNxfzG5DXJJwBmC/m-kus/map",
			metadata: meta.Metadata{
				"0":       &meta.NodeMetadata{FieldName: "account", Prim: "pair", Args: []string{"0/0", "0/1"}, Type: "namedtuple"},
				"0/0":     &meta.NodeMetadata{FieldName: "settings", Prim: "map", Type: "map", Name: "settings"},
				"0/0/k":   &meta.NodeMetadata{Prim: "string", Type: "string"},
				"0/0/v":   &meta.NodeMetadata{TypeName: "value", Prim: "or", Args: []string{"0/0/v/0", "0/0/v/1"}, Type: "union"},
				"0/0/v/0": &meta.NodeMetadata{Prim: "string", Type: "string"},
				"0/0/v/1": &meta.NodeMetadata{Prim: "int", Type: "int"},
				"0/1":     &meta.NodeMetadata{FieldName: "id", Prim: "nat", Type: "nat", Name: "id"},
			},
			result: `[{"name":"default","typedef":[{"name":"default","type":"pair","args":[{"key":"settings","value":"$settings"},{"key":"id","value":"nat"}]},{"name":"settings","type":"map","args":[{"key":"key","value":"string"},{"key":"value","value":"or(string, int)"}]}],"bin_path":"0"}]`,
		},
		{
			name: "carthagenet/KT1Dz3cPcz51kTA3tyjwNzkBWo8k7TG5UxMK/m-kus/args#",
			metadata: meta.Metadata{
				"0":           &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0", "0/1/0", "0/1/1"}, Type: "tuple"},
				"0/0":         &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1":         &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0":       &meta.NodeMetadata{Prim: "string", Type: "string"},
				"0/1/1":       &meta.NodeMetadata{Prim: "big_map", Type: "big_map"},
				"0/1/1/k":     &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/v":     &meta.NodeMetadata{Prim: "pair", Args: []string{"0/1/1/v/0", "0/1/1/v/1"}, Type: "tuple"},
				"0/1/1/v/0":   &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/1/v/1":   &meta.NodeMetadata{Prim: "map", Type: "map"},
				"0/1/1/v/1/k": &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/v/1/v": &meta.NodeMetadata{Prim: "nat", Type: "nat"},
			},
			result: `[{"name":"default","typedef":[{"name":"default","type":"pair","args":[{"value":"nat"},{"value":"string"},{"value":"$pair0_arg2"}]},{"name":"pair0_arg2","type":"big_map","args":[{"key":"key","value":"address"},{"key":"value","value":"$big_map1_value"}]},{"name":"big_map1_value","type":"pair","args":[{"value":"nat"},{"value":"map(address, nat)"}]}],"bin_path":"0"}]`,
		},
		{
			name: "carthagenet/KT1PpNh5jGx5DhPkpvVo374B6Bbk3H3aZAtu/eurotz",
			metadata: meta.Metadata{
				"0":                 &meta.NodeMetadata{Prim: "or", Args: []string{"0/0/0/0/0", "0/0/0/0/1", "0/0/0/1/0", "0/0/0/1/1", "0/0/1/0/0", "0/0/1/0/1", "0/0/1/1/0", "0/0/1/1/1/0", "0/0/1/1/1/1", "0/1/0/0/0", "0/1/0/0/1", "0/1/0/1/0", "0/1/0/1/1/0", "0/1/0/1/1/1", "0/1/1/0/0", "0/1/1/0/1", "0/1/1/1/0", "0/1/1/1/1/0", "0/1/1/1/1/1"}, Type: "namedunion"},
				"0/0":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/0/0":         &meta.NodeMetadata{FieldName: "addSuperTransferAgent", Prim: "address", Type: "address", Name: "addSuperTransferAgent"},
				"0/0/0/0/1":         &meta.NodeMetadata{FieldName: "addTransferAgent", Prim: "address", Type: "address", Name: "addTransferAgent"},
				"0/0/0/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/0/1/0":         &meta.NodeMetadata{FieldName: "approve", Prim: "pair", Args: []string{"0/0/0/1/0/0", "0/0/0/1/0/1/0", "0/0/0/1/0/1/1"}, Type: "namedtuple", Name: "approve"},
				"0/0/0/1/0/0":       &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/0/0/1/0/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/0/1/0":     &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/0/0/1/0/1/1":     &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/0/0/1/1":         &meta.NodeMetadata{FieldName: "approveFeeless", Prim: "pair", Args: []string{"0/0/0/1/1/0/0", "0/0/0/1/1/0/1/0", "0/0/0/1/1/0/1/1", "0/0/0/1/1/1/0/0", "0/0/0/1/1/1/0/1", "0/0/0/1/1/1/1/0", "0/0/0/1/1/1/1/1"}, Type: "namedtuple", Name: "approveFeeless"},
				"0/0/0/1/1/0":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/1/0/0":     &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/0/0/1/1/0/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/1/0/1/0":   &meta.NodeMetadata{FieldName: "b", Prim: "bytes", Type: "bytes", Name: "b"},
				"0/0/0/1/1/0/1/1":   &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/0/0/1/1/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/1/1/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/1/1/0/0":   &meta.NodeMetadata{FieldName: "k", Prim: "key", Type: "key", Name: "k"},
				"0/0/0/1/1/1/0/1":   &meta.NodeMetadata{FieldName: "nonce", Prim: "nat", Type: "nat", Name: "nonce"},
				"0/0/0/1/1/1/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/0/1/1/1/1/0":   &meta.NodeMetadata{FieldName: "s", Prim: "signature", Type: "signature", Name: "s"},
				"0/0/0/1/1/1/1/1":   &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/0/1":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/0/0":         &meta.NodeMetadata{FieldName: "burn", Prim: "pair", Args: []string{"0/0/1/0/0/0", "0/0/1/0/0/1"}, Type: "namedtuple", Name: "burn"},
				"0/0/1/0/0/0":       &meta.NodeMetadata{FieldName: "address", Prim: "address", Type: "address", Name: "address"},
				"0/0/1/0/0/1":       &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/0/1/0/1":         &meta.NodeMetadata{FieldName: "changeEventSinkContractAddress", Prim: "address", Type: "address", Name: "changeEventSinkContractAddress"},
				"0/0/1/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/1/0":         &meta.NodeMetadata{FieldName: "decreaseAllowance", Prim: "pair", Args: []string{"0/0/1/1/0/0", "0/0/1/1/0/1/0", "0/0/1/1/0/1/1"}, Type: "namedtuple", Name: "decreaseAllowance"},
				"0/0/1/1/0/0":       &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/0/1/1/0/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/1/0/1/0":     &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/0/1/1/0/1/1":     &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/0/1/1/1":         &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1/1/1/0":       &meta.NodeMetadata{FieldName: "decreaseAllowanceFeeless", Prim: "pair", Args: []string{"0/0/1/1/1/0/0/0", "0/0/1/1/1/0/0/1/0", "0/0/1/1/1/0/0/1/1", "0/0/1/1/1/0/1/0/0", "0/0/1/1/1/0/1/0/1", "0/0/1/1/1/0/1/1/0", "0/0/1/1/1/0/1/1/1"}, Type: "namedtuple", Name: "decreaseAllowanceFeeless"},
				"0/0/1/1/1/0/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/1/1/0/0/0":   &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/0/1/1/1/0/0/1":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/1/1/0/0/1/0": &meta.NodeMetadata{FieldName: "b", Prim: "bytes", Type: "bytes", Name: "b"},
				"0/0/1/1/1/0/0/1/1": &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/0/1/1/1/0/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/1/1/0/1/0":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/1/1/0/1/0/0": &meta.NodeMetadata{FieldName: "k", Prim: "key", Type: "key", Name: "k"},
				"0/0/1/1/1/0/1/0/1": &meta.NodeMetadata{FieldName: "nonce", Prim: "nat", Type: "nat", Name: "nonce"},
				"0/0/1/1/1/0/1/1":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/0/1/1/1/0/1/1/0": &meta.NodeMetadata{FieldName: "s", Prim: "signature", Type: "signature", Name: "s"},
				"0/0/1/1/1/0/1/1/1": &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/0/1/1/1/1":       &meta.NodeMetadata{FieldName: "deleteSuperTransferAgent", Prim: "address", Type: "address", Name: "deleteSuperTransferAgent"},
				"0/1":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0/0/0":         &meta.NodeMetadata{FieldName: "deleteTransferAgent", Prim: "address", Type: "address", Name: "deleteTransferAgent"},
				"0/1/0/0/1":         &meta.NodeMetadata{FieldName: "increaseAllowance", Prim: "pair", Args: []string{"0/1/0/0/1/0", "0/1/0/0/1/1/0", "0/1/0/0/1/1/1"}, Type: "namedtuple", Name: "increaseAllowance"},
				"0/1/0/0/1/0":       &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/1/0/0/1/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/0/1/1/0":     &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/1/0/0/1/1/1":     &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/1/0/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0/1/0":         &meta.NodeMetadata{FieldName: "increaseAllowanceFeeless", Prim: "pair", Args: []string{"0/1/0/1/0/0/0", "0/1/0/1/0/0/1/0", "0/1/0/1/0/0/1/1", "0/1/0/1/0/1/0/0", "0/1/0/1/0/1/0/1", "0/1/0/1/0/1/1/0", "0/1/0/1/0/1/1/1"}, Type: "namedtuple", Name: "increaseAllowanceFeeless"},
				"0/1/0/1/0/0":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/1/0/0/0":     &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/1/0/1/0/0/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/1/0/0/1/0":   &meta.NodeMetadata{FieldName: "b", Prim: "bytes", Type: "bytes", Name: "b"},
				"0/1/0/1/0/0/1/1":   &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/1/0/1/0/1":       &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/1/0/1/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/1/0/1/0/0":   &meta.NodeMetadata{FieldName: "k", Prim: "key", Type: "key", Name: "k"},
				"0/1/0/1/0/1/0/1":   &meta.NodeMetadata{FieldName: "nonce", Prim: "nat", Type: "nat", Name: "nonce"},
				"0/1/0/1/0/1/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/0/1/0/1/1/0":   &meta.NodeMetadata{FieldName: "s", Prim: "signature", Type: "signature", Name: "s"},
				"0/1/0/1/0/1/1/1":   &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/1/0/1/1":         &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/0/1/1/0":       &meta.NodeMetadata{FieldName: "mint", Prim: "pair", Args: []string{"0/1/0/1/1/0/0", "0/1/0/1/1/0/1"}, Type: "namedtuple", Name: "mint"},
				"0/1/0/1/1/0/0":     &meta.NodeMetadata{FieldName: "address", Prim: "address", Type: "address", Name: "address"},
				"0/1/0/1/1/0/1":     &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/1/0/1/1/1":       &meta.NodeMetadata{FieldName: "resetAllAllowances", Prim: "address", Type: "address", Name: "resetAllAllowances"},
				"0/1/1":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/0/0":         &meta.NodeMetadata{FieldName: "resetAllowance", Prim: "pair", Args: []string{"0/1/1/0/0/0", "0/1/1/0/0/1"}, Type: "namedtuple", Name: "resetAllowance"},
				"0/1/1/0/0/0":       &meta.NodeMetadata{FieldName: "address", Prim: "address", Type: "address", Name: "address"},
				"0/1/1/0/0/1":       &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/1/1/0/1":         &meta.NodeMetadata{FieldName: "setAdministrator", Prim: "address", Type: "address", Name: "setAdministrator"},
				"0/1/1/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/0":         &meta.NodeMetadata{FieldName: "setPause", Prim: "bool", Type: "bool", Name: "setPause"},
				"0/1/1/1/1":         &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0":       &meta.NodeMetadata{FieldName: "transfer", Prim: "pair", Args: []string{"0/1/1/1/1/0/0", "0/1/1/1/1/0/1/0", "0/1/1/1/1/0/1/1"}, Type: "namedtuple", Name: "transfer"},
				"0/1/1/1/1/0/0":     &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/1/1/1/1/0/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/0/1/0":   &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/1/1/1/1/0/1/1":   &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
				"0/1/1/1/1/1":       &meta.NodeMetadata{FieldName: "transferFeeless", Prim: "pair", Args: []string{"0/1/1/1/1/1/0/0", "0/1/1/1/1/1/0/1/0", "0/1/1/1/1/1/0/1/1", "0/1/1/1/1/1/1/0/0", "0/1/1/1/1/1/1/0/1", "0/1/1/1/1/1/1/1/0", "0/1/1/1/1/1/1/1/1"}, Type: "namedtuple", Name: "transferFeeless"},
				"0/1/1/1/1/1/0":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/1/0/0":   &meta.NodeMetadata{FieldName: "amount", Prim: "int", Type: "int", Name: "amount"},
				"0/1/1/1/1/1/0/1":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/1/0/1/0": &meta.NodeMetadata{FieldName: "b", Prim: "bytes", Type: "bytes", Name: "b"},
				"0/1/1/1/1/1/0/1/1": &meta.NodeMetadata{FieldName: "f", Prim: "address", Type: "address", Name: "f"},
				"0/1/1/1/1/1/1":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/1/1/0":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/1/1/0/0": &meta.NodeMetadata{FieldName: "k", Prim: "key", Type: "key", Name: "k"},
				"0/1/1/1/1/1/1/0/1": &meta.NodeMetadata{FieldName: "nonce", Prim: "nat", Type: "nat", Name: "nonce"},
				"0/1/1/1/1/1/1/1":   &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/1/1/1/0": &meta.NodeMetadata{FieldName: "s", Prim: "signature", Type: "signature", Name: "s"},
				"0/1/1/1/1/1/1/1/1": &meta.NodeMetadata{FieldName: "t", Prim: "address", Type: "address", Name: "t"},
			},
			result: `[{"name":"addSuperTransferAgent","typedef":[{"name":"addSuperTransferAgent","type":"address"}],"bin_path":"0/0/0/0/0"},{"name":"addTransferAgent","typedef":[{"name":"addTransferAgent","type":"address"}],"bin_path":"0/0/0/0/1"},{"name":"approve","typedef":[{"name":"approve","type":"pair","args":[{"key":"amount","value":"int"},{"key":"f","value":"address"},{"key":"t","value":"address"}]}],"bin_path":"0/0/0/1/0"},{"name":"approveFeeless","typedef":[{"name":"approveFeeless","type":"pair","args":[{"key":"amount","value":"int"},{"key":"b","value":"bytes"},{"key":"f","value":"address"},{"key":"k","value":"key"},{"key":"nonce","value":"nat"},{"key":"s","value":"signature"},{"key":"t","value":"address"}]}],"bin_path":"0/0/0/1/1"},{"name":"burn","typedef":[{"name":"burn","type":"pair","args":[{"key":"address","value":"address"},{"key":"amount","value":"int"}]}],"bin_path":"0/0/1/0/0"},{"name":"changeEventSinkContractAddress","typedef":[{"name":"changeEventSinkContractAddress","type":"address"}],"bin_path":"0/0/1/0/1"},{"name":"decreaseAllowance","typedef":[{"name":"decreaseAllowance","type":"pair","args":[{"key":"amount","value":"int"},{"key":"f","value":"address"},{"key":"t","value":"address"}]}],"bin_path":"0/0/1/1/0"},{"name":"decreaseAllowanceFeeless","typedef":[{"name":"decreaseAllowanceFeeless","type":"pair","args":[{"key":"amount","value":"int"},{"key":"b","value":"bytes"},{"key":"f","value":"address"},{"key":"k","value":"key"},{"key":"nonce","value":"nat"},{"key":"s","value":"signature"},{"key":"t","value":"address"}]}],"bin_path":"0/0/1/1/1/0"},{"name":"deleteSuperTransferAgent","typedef":[{"name":"deleteSuperTransferAgent","type":"address"}],"bin_path":"0/0/1/1/1/1"},{"name":"deleteTransferAgent","typedef":[{"name":"deleteTransferAgent","type":"address"}],"bin_path":"0/1/0/0/0"},{"name":"increaseAllowance","typedef":[{"name":"increaseAllowance","type":"pair","args":[{"key":"amount","value":"int"},{"key":"f","value":"address"},{"key":"t","value":"address"}]}],"bin_path":"0/1/0/0/1"},{"name":"increaseAllowanceFeeless","typedef":[{"name":"increaseAllowanceFeeless","type":"pair","args":[{"key":"amount","value":"int"},{"key":"b","value":"bytes"},{"key":"f","value":"address"},{"key":"k","value":"key"},{"key":"nonce","value":"nat"},{"key":"s","value":"signature"},{"key":"t","value":"address"}]}],"bin_path":"0/1/0/1/0"},{"name":"mint","typedef":[{"name":"mint","type":"pair","args":[{"key":"address","value":"address"},{"key":"amount","value":"int"}]}],"bin_path":"0/1/0/1/1/0"},{"name":"resetAllAllowances","typedef":[{"name":"resetAllAllowances","type":"address"}],"bin_path":"0/1/0/1/1/1"},{"name":"resetAllowance","typedef":[{"name":"resetAllowance","type":"pair","args":[{"key":"address","value":"address"},{"key":"f","value":"address"}]}],"bin_path":"0/1/1/0/0"},{"name":"setAdministrator","typedef":[{"name":"setAdministrator","type":"address"}],"bin_path":"0/1/1/0/1"},{"name":"setPause","typedef":[{"name":"setPause","type":"bool"}],"bin_path":"0/1/1/1/0"},{"name":"transfer","typedef":[{"name":"transfer","type":"pair","args":[{"key":"amount","value":"int"},{"key":"f","value":"address"},{"key":"t","value":"address"}]}],"bin_path":"0/1/1/1/1/0"},{"name":"transferFeeless","typedef":[{"name":"transferFeeless","type":"pair","args":[{"key":"amount","value":"int"},{"key":"b","value":"bytes"},{"key":"f","value":"address"},{"key":"k","value":"key"},{"key":"nonce","value":"nat"},{"key":"s","value":"signature"},{"key":"t","value":"address"}]}],"bin_path":"0/1/1/1/1/1"}]`,
		},
		{
			name: "bigmap/carthagenet/3520",
			metadata: meta.Metadata{
				"0":     &meta.NodeMetadata{Prim: "big_map", Type: "big_map"},
				"0/k":   &meta.NodeMetadata{Prim: "pair", Args: []string{"0/k/0", "0/k/1"}, Type: "namedtuple"},
				"0/k/0": &meta.NodeMetadata{FieldName: "test", Prim: "string", Type: "string", Name: "test"},
				"0/k/1": &meta.NodeMetadata{FieldName: "test2", Prim: "string", Type: "string", Name: "test2"},
				"0/v":   &meta.NodeMetadata{Prim: "string", Type: "string"},
			},
			result: `[{"name":"default","typedef":[{"name":"default","type":"big_map","args":[{"key":"key","value":"$default_key"},{"key":"value","value":"string"}]},{"name":"default_key","type":"pair","args":[{"key":"test","value":"string"},{"key":"test2","value":"string"}]}],"bin_path":"0"}]`,
		},
		{
			name: "carthagenet/KT19VhYSGKmrdFRrEcqQTpEoTJcR6PnCLdCe",
			metadata: meta.Metadata{
				"0/1/1/1/0/1/0/0":       &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/1/1/0/1/0/1":       &meta.NodeMetadata{Prim: "option", Type: "option"},
				"0/1/1/1/0/1/0/1/o/1":   &meta.NodeMetadata{Prim: "set", Type: "set"},
				"0/0/1/l":               &meta.NodeMetadata{Prim: "pair", Args: []string{"0/0/1/l/0", "0/0/1/l/1"}, Type: "tuple"},
				"0/0/1/l/1":             &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/0":               &meta.NodeMetadata{FieldName: "assertReceivers", Prim: "list", Type: "list", Name: "assertReceivers"},
				"0/1/1/1/0":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/0/0/1/1":       &meta.NodeMetadata{Prim: "option", Type: "option"},
				"0/1/1/1/0/1/0/1/o/1/s": &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/1/1/0/1/1":         &meta.NodeMetadata{FieldName: "setAdmin", Prim: "address", Type: "address", Name: "setAdmin"},
				"0/1/1/1/1/0/1/0":       &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/1/1/0/0/0":       &meta.NodeMetadata{Prim: "unit", Type: "unit"},
				"0/1/1/1/1/1/1/1":       &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"address\"}", Type: "contract"},
				"0/0/0/1":               &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/0/l":             &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/1/1/1/0/1":       &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"option\",\"args\":[{\"prim\":\"pair\",\"args\":[{\"prim\":\"bool\"},{\"prim\":\"set\",\"args\":[{\"prim\":\"nat\"}]}]}]}", Type: "contract"},
				"0/1/1/1/0/0/1/1/o":     &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/1/1/1":             &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0/0":         &meta.NodeMetadata{FieldName: "getIssuer", Prim: "pair", Args: []string{"0/1/1/1/1/0/0/0", "0/1/1/1/1/0/0/1"}, Type: "tuple", Name: "getIssuer"},
				"0/1/1/1/1/0/0/1":       &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"address\"}", Type: "contract"},
				"0/1/1/1/1/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/0/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/0/0/0":         &meta.NodeMetadata{FieldName: "setIssuer", Prim: "address", Type: "address", Name: "setIssuer"},
				"0/1/1/1/0/0/1/0":       &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/1/1/0/1/0/1/o":     &meta.NodeMetadata{Prim: "pair", Type: "pair"},
				"0/1/1/1/1/1/0/0":       &meta.NodeMetadata{Prim: "nat", Type: "nat"},
				"0/1/1/1/1/1/1":         &meta.NodeMetadata{FieldName: "getAdmin", Prim: "pair", Args: []string{"0/1/1/1/1/1/1/0", "0/1/1/1/1/1/1/1"}, Type: "tuple", Name: "getAdmin"},
				"0/0":                   &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/0/1":                 &meta.NodeMetadata{FieldName: "assertTransfers", Prim: "list", Type: "list", Name: "assertTransfers"},
				"0/1":                   &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/0/1":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/0":           &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0":                     &meta.NodeMetadata{Prim: "or", Args: []string{"0/0/0", "0/0/1", "0/1/0", "0/1/1/0", "0/1/1/1/0/0/0", "0/1/1/1/0/0/1", "0/1/1/1/0/1/0", "0/1/1/1/0/1/1", "0/1/1/1/1/0/0", "0/1/1/1/1/0/1", "0/1/1/1/1/1/0", "0/1/1/1/1/1/1"}, Type: "namedunion"},
				"0/0/0":                 &meta.NodeMetadata{FieldName: "assertTransfer", Prim: "pair", Args: []string{"0/0/0/0", "0/0/0/1"}, Type: "tuple", Name: "assertTransfer"},
				"0/1/1/1/0/1/0":         &meta.NodeMetadata{FieldName: "setWhitelistOutbound", Prim: "pair", Args: []string{"0/1/1/1/0/1/0/0", "0/1/1/1/0/1/0/1/o/0", "0/1/1/1/0/1/0/1/o/1"}, Type: "tuple", Name: "setWhitelistOutbound"},
				"0/1/1/1/1/0/1":         &meta.NodeMetadata{FieldName: "getUser", Prim: "pair", Args: []string{"0/1/1/1/1/0/1/0", "0/1/1/1/1/0/1/1"}, Type: "tuple", Name: "getUser"},
				"0/1/1/1/0/0/1":         &meta.NodeMetadata{FieldName: "addUser", Prim: "pair", Args: []string{"0/1/1/1/0/0/1/0", "0/1/1/1/0/0/1/1/o"}, Type: "tuple", Name: "addUser"},
				"0/1/1/1/0/1/0/1/o/0":   &meta.NodeMetadata{Prim: "bool", Type: "bool"},
				"0/1/1/1/1/0/1/1":       &meta.NodeMetadata{Prim: "contract", Parameter: "{\"prim\":\"option\",\"args\":[{\"prim\":\"nat\"}]}", Type: "contract"},
				"0/0/0/0":               &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/0/1/l/0":             &meta.NodeMetadata{Prim: "address", Type: "address"},
				"0/1/0":                 &meta.NodeMetadata{FieldName: "assertReceiver", Prim: "address", Type: "address", Name: "assertReceiver"},
				"0/1/1":                 &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1":               &meta.NodeMetadata{Prim: "or", Type: "or"},
				"0/1/1/1/1/1/0":         &meta.NodeMetadata{FieldName: "getWhitelist", Prim: "pair", Args: []string{"0/1/1/1/1/1/0/0", "0/1/1/1/1/1/0/1"}, Type: "tuple", Name: "getWhitelist"},
				"0/1/1/1/1/1/1/0":       &meta.NodeMetadata{Prim: "unit", Type: "unit"},
			},
			result: `[{"name":"assertTransfer","typedef":[{"name":"assertTransfer","type":"pair(address, address)"}],"bin_path":"0/0/0"},{"name":"assertTransfers","typedef":[{"name":"assertTransfers","type":"list(pair(address, address))"}],"bin_path":"0/0/1"},{"name":"assertReceiver","typedef":[{"name":"assertReceiver","type":"address"}],"bin_path":"0/1/0"},{"name":"assertReceivers","typedef":[{"name":"assertReceivers","type":"list(address)"}],"bin_path":"0/1/1/0"},{"name":"setIssuer","typedef":[{"name":"setIssuer","type":"address"}],"bin_path":"0/1/1/1/0/0/0"},{"name":"addUser","typedef":[{"name":"addUser","type":"pair","args":[{"value":"address"},{"value":"option(nat)"}]}],"bin_path":"0/1/1/1/0/0/1"},{"name":"setWhitelistOutbound","typedef":[{"name":"setWhitelistOutbound","type":"pair","args":[{"value":"nat"},{"value":"bool"},{"value":"set(nat)"}]}],"bin_path":"0/1/1/1/0/1/0"},{"name":"setAdmin","typedef":[{"name":"setAdmin","type":"address"}],"bin_path":"0/1/1/1/0/1/1"},{"name":"getIssuer","typedef":[{"name":"getIssuer","type":"pair","args":[{"value":"unit"},{"value":"contract(address)"}]}],"bin_path":"0/1/1/1/1/0/0"},{"name":"getUser","typedef":[{"name":"getUser","type":"pair","args":[{"value":"address"},{"value":"contract($contract0_param)"}]},{"name":"contract0_param","type":"option nat"}],"bin_path":"0/1/1/1/1/0/1"},{"name":"getWhitelist","typedef":[{"name":"getWhitelist","type":"pair","args":[{"value":"nat"},{"value":"contract($contract0_param)"}]},{"name":"contract0_param","type":"option (pair bool (set nat))"}],"bin_path":"0/1/1/1/1/1/0"},{"name":"getAdmin","typedef":[{"name":"getAdmin","type":"pair","args":[{"value":"unit"},{"value":"contract(address)"}]}],"bin_path":"0/1/1/1/1/1/1"}]`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entrypoints, err := GetEntrypoints(tt.metadata)
			if err != nil {
				t.Errorf("GetDocEntrypoints error: %v", err)
				return
			}

			json, err := json.Marshal(entrypoints)
			if err != nil {
				t.Errorf("json.Marshal error: %v", err)
				return
			}

			if tt.result != string(json) {
				t.Errorf("invalid json = %s\nwant = %s", tt.result, string(json))
			}
		})
	}
}

func TestGetTypedef(t *testing.T) {
	tests := []struct {
		name     string
		binPath  string
		metadata meta.Metadata
		result   string
	}{
		{
			name:    "bigmap/carthagenet/3520",
			binPath: "0",
			metadata: meta.Metadata{
				"0":     &meta.NodeMetadata{Prim: "big_map", Type: "big_map"},
				"0/k":   &meta.NodeMetadata{Prim: "pair", Args: []string{"0/k/0", "0/k/1"}, Type: "namedtuple"},
				"0/k/0": &meta.NodeMetadata{FieldName: "test", Prim: "string", Type: "string", Name: "test"},
				"0/k/1": &meta.NodeMetadata{FieldName: "test2", Prim: "string", Type: "string", Name: "test2"},
				"0/v":   &meta.NodeMetadata{Prim: "string", Type: "string"},
			},
			result: `[{"name":"default","type":"big_map","args":[{"key":"key","value":"$default_key"},{"key":"value","value":"string"}]},{"name":"default_key","type":"pair","args":[{"key":"test","value":"string"},{"key":"test2","value":"string"}]}]`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			typedef, err := GetTypedef(tt.binPath, tt.metadata)
			if err != nil {
				t.Errorf("GetTypedef error %v", err)
				return
			}

			json, err := json.Marshal(typedef)
			if err != nil {
				t.Errorf("json.Marshal error: %v", err)
				return
			}

			if string(json) != tt.result {
				t.Errorf("invalid json")
			}
		})
	}
}
