name: Release
permissions:
  contents: write
  pull-requests: read
on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish Github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        continue-on-error: true
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            BCD ${{ env.RELEASE_VERSION }} has been released 🚀
            More info at https://github.com/baking-bad/bcdhub/releases/tag/${{ env.RELEASE_VERSION }}
