name: Test
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches-ignore:
      - master

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.3
          args: --timeout=5m

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
          cache: true
      - name: Run tests
        run: |
          go mod download
          go test ./...
